/* =========================================================================
   VERBATIM · Candidate profile corpus (baked in so file:// stays offline)
   Sources: "CV Jordi Marsal 2026-08 Python Senior ES/EN.docx" + docs/CV_26.md.
   Bilingual (es/en): the Coach reads the corpus that matches the interview
   language, so the prompt never mixes languages and the answer never drifts.
   Condensed but faithful: no invented data — the "cv" answer may ONLY rely
   on this corpus.
   ========================================================================= */
(function () {
  "use strict";
  window.VERBATIM_CV = {
    es: [
      "Jordi Marçal Poy — Desarrollador backend con más de 8 años de experiencia diseñando APIs REST y microservicios con Java (Spring Boot) y Python, y construyendo herramientas de automatización y testing. Máster en Ciencia de Datos (UOC). Aplica SOLID, Clean Code y TDD; mentoría a desarrolladores junior.",
      "COMPETENCIAS — Java: 11/21, Spring Boot 2/3, Play Framework, Spring-Cloud, Reactor, CompletableFuture, arquitecturas por capas y hexagonal. Python: FastAPI (async), Flask, SQLAlchemy (AsyncSession), PyMongo, Pydantic, Click, Poetry, pytest, mypy strict, ruff, black, pre-commit. Node/TypeScript: Node.js 24, Serverless Framework, AWS Lambda, Jest. APIs y datos: REST, OpenAPI/Swagger v2-v3, ORM, MongoDB, MySQL, Redis, Elasticsearch. DevOps: Git, CI/CD (Jenkins, GitHub Actions), Docker, Kubernetes, Ansible, RabbitMQ. Calidad: TDD, pytest/JUnit 5/Mockito, SonarQube/SonarLint.",
      "TELEFÓNICA KERNEL — OPEN GATEWAY (May 2022 - actualidad): diseño y construcción de microservicios adaptadores REST que exponen las APIs de Open Gateway por país. Autor y mantenedor de una suite de 12+ herramientas CLI en Python (Poetry, imagen Docker) para operar ~90 adaptadores en 4 países y 5-6 entornos: verificación de despliegues, checks de pre-deploy, gestión de dependencias entre adaptadores, consultas a BD y tooling Kibana/Elasticsearch. Generación automática de documentación y diagramas de secuencia integrada en CI/CD (Jenkins); adaptación del generador de código OpenAPI (Swagger v2/v3) para Play Framework, Spring Boot y Kotlin; mocks automáticos en Next.js. Programación reactiva con Reactor y CompletableFuture. Revisiones de código aplicando SOLID y patrones.",
      "AXPE CONSULTING (Ene 2026 - May 2026, cliente Mapfre): modernización de 39 APIs corporativas a Node.js 24 — análisis de repositorios, validación de ramas/PRs, Serverless Framework, AWS (Lambda, CDK, CloudFormation, API Gateway), TypeScript, trazabilidad y reporting técnico.",
      "ZITRO LABORATORY (Nov 2020 - May 2022): servidor Java del motor de apuestas, Backoffice e integraciones con casinos online con dinero real; Apple Sign-In server-to-server, históricos AWS Snowflake + Cassandra, OneSignal; Java 11-13, Spring Boot 2.4, MongoDB, Redis, Cassandra, MySQL, RabbitMQ, scripting Python/Bash.",
      "ATTENDRE S.L. (May 2017 - Nov 2020): evolución de Attend® (gestión de tickets, inventario y proyectos para ayuntamientos); License Manager (Spring Boot 2.3 + REST), app de actualización REST, instalador JavaFX, apps Android 4.4-10; Java 7-8, Stripes, Hibernate, MS-SQL/Oracle/MySQL, migración de datos con Python.",
      "PROYECTOS PERSONALES (PYTHON): API REST async con FastAPI + SQLAlchemy AsyncSession (acortador de URLs, arquitectura en capas, OpenAPI automática, pytest). md-mermaid-pdf (MIT): CLI que renderiza Markdown+Mermaid a PDF con TDD, mypy strict, ruff, pre-commit y CI en GitHub Actions. Rest360 (TFM): API Flask + PyMongo sobre MongoDB para dominio bancario. Análisis de datos y ML: NLP con NLTK (LDA, sentimiento), PyTorch, pandas, scikit-learn.",
      "FORMACIÓN: Máster en Ciencia de Datos (UOC 2019); Grado en Ingeniería Informática (UOC 2017); Bootcamp Data Analytics Ironhack; Técnico en Deep Learning 300h (UOC). IDIOMAS: catalán y castellano nativos; francés B2; inglés B2 (listening/reading/writing alto, speaking medio)."
    ].join("\n"),
    en: [
      "Jordi Marçal Poy — Backend developer with 8+ years of experience designing REST APIs and microservices with Java (Spring Boot) and Python, and building automation and testing tooling. MSc in Data Science (UOC). Applies SOLID, Clean Code and TDD; mentors junior developers.",
      "SKILLS — Java: 11/21, Spring Boot 2/3, Play Framework, Spring-Cloud, Reactor, CompletableFuture, layered and hexagonal architectures. Python: FastAPI (async), Flask, SQLAlchemy (AsyncSession), PyMongo, Pydantic, Click, Poetry, pytest, strict mypy, ruff, black, pre-commit. Node/TypeScript: Node.js 24, Serverless Framework, AWS Lambda, Jest. APIs and data: REST, OpenAPI/Swagger v2-v3, ORM, MongoDB, MySQL, Redis, Elasticsearch. DevOps: Git, CI/CD (Jenkins, GitHub Actions), Docker, Kubernetes, Ansible, RabbitMQ. Quality: TDD, pytest/JUnit 5/Mockito, SonarQube/SonarLint.",
      "TELEFÓNICA KERNEL — OPEN GATEWAY (May 2022 - present): design and build of REST adapter microservices exposing Open Gateway APIs per country. Author and maintainer of a suite of 12+ Python CLI tools (Poetry, Docker image) to operate ~90 adapters across 4 countries and 5-6 environments each: deployment verification, pre-deploy checks, dependency management between adapters, database queries and Kibana/Elasticsearch tooling. Automatic generation of documentation and sequence diagrams integrated into CI/CD (Jenkins); adaptation of the OpenAPI code generator (Swagger v2/v3) for Play Framework, Spring Boot and Kotlin; automatic Next.js mocks. Reactive programming with Reactor and CompletableFuture. Code reviews applying SOLID and design patterns.",
      "AXPE CONSULTING (Jan 2026 - May 2026, client Mapfre): modernization of 39 corporate APIs to Node.js 24 — repository analysis, branch/PR validation, Serverless Framework, AWS (Lambda, CDK, CloudFormation, API Gateway), TypeScript, technical traceability and reporting.",
      "ZITRO LABORATORY (Nov 2020 - May 2022): Java server for the betting engine, Backoffice and integrations with online casinos with real money; Apple Sign-In server-to-server, AWS Snowflake + Cassandra histories, OneSignal; Java 11-13, Spring Boot 2.4, MongoDB, Redis, Cassandra, MySQL, RabbitMQ, Python/Bash scripting.",
      "ATTENDRE S.L. (May 2017 - Nov 2020): evolution of Attend® (ticket, inventory and project management for city councils); License Manager (Spring Boot 2.3 + REST), REST updater app, JavaFX installer, Android apps 4.4-10; Java 7-8, Stripes, Hibernate, MS-SQL/Oracle/MySQL, data migration with Python.",
      "PERSONAL PROJECTS (PYTHON): async REST API with FastAPI + SQLAlchemy AsyncSession (URL shortener, layered architecture, automatic OpenAPI docs, pytest). md-mermaid-pdf (MIT): CLI that renders Markdown+Mermaid diagrams to PDF with TDD, strict mypy, ruff, pre-commit and GitHub Actions CI. Rest360 (MSc thesis): Flask API + PyMongo over MongoDB for a banking domain. Data analysis and ML: NLP with NLTK (LDA, sentiment), PyTorch, pandas, scikit-learn.",
      "EDUCATION: MSc in Data Science (UOC 2019); BSc in Computer Engineering (UOC 2017); Ironhack Data Analytics Bootcamp; Deep Learning Technician 300h (UOC). LANGUAGES: Catalan and Spanish (native); French B2; English B2 (high listening/reading/writing, medium speaking)."
    ].join("\n")
  };
})();
