/* =========================================================================
   VERBATIM · i18n core
   Single source of truth for every UI string. Pages stay declarative;
   this module applies the active locale and wires the language switch.
   Keys are stable across pages so the same key can be reused anywhere.
   ========================================================================= */
(function () {
  "use strict";

  const STRINGS = {
    /* ---------------- Landing ---------------- */
    site_title: {
      es: "VERBATIM · Voice Interview Simulator",
      en: "VERBATIM · Voice Interview Simulator"
    },
    nav_features: { es: "Funcionalidad", en: "Features" },
    nav_how: { es: "Cómo funciona", en: "How it works" },
    nav_setup: { es: "Configuración", en: "Setup" },
    nav_start: { es: "Empezar entrevista", en: "Start interview" },
    nav_start2: { es: "Empezar", en: "Start" },
    hero_eyebrow: {
      es: "Simulador de entrevistas por voz · IA en tu navegador",
      en: "Voice-driven interview simulator · AI in your browser"
    },
    hero_title: {
      es: "Una entrevista que<br><em>te escucha</em>",
      en: "An interview that<br><em>actually listens</em>"
    },
    hero_lede: {
      es: "Un entrevistador automático te pregunta, tú respondes al habla, y un agente lo valora en tiempo real. En castellano o inglés. Sin servidores, sin cuentas, sin fricción.",
      en: "An automatic interviewer asks, you answer out loud, and an agent scores every turn — in real time. In Spanish or English. No servers, no accounts, no friction."
    },
    cta_start: { es: "Empezar una entrevista", en: "Start an interview" },
    cta_learn: { es: "Cómo funciona", en: "How it works" },
    cta_start_again: { es: "Empezar una entrevista", en: "Start an interview" },
    m1_b: { es: "0&nbsp;servidores", en: "0&nbsp;servers" },
    m1_s: { es: "Se abre con doble clic", en: "Opens with a double-click" },
    m2_b: { es: "ES · EN", en: "ES · EN" },
    m2_s: { es: "Entrevista bilingüe", en: "Bilingual interview" },
    m3_b: { es: "Whisper", en: "Whisper" },
    m3_s: { es: "Transcripción por voz", en: "Speech transcription" },

    feat_head: {
      es: "Conversación real, con oreja inteligente",
      en: "Real conversation, with a brain behind it"
    },
    feat_lede: {
      es: "No es un chatbot con iconos. Es una sesión de voz donde cada turno se escucha, se transcribe y se valora.",
      en: "Not a chatbot with icons. A voice session where every turn is heard, transcribed and scored."
    },
    feat1_h: { es: "El entrevistador habla", en: "The interviewer speaks" },
    feat1_p: {
      es: "Preguntas generadas por un agente, pronunciadas en el idioma elegido. Pulsa de nuevo para reproducir la pregunta.",
      en: "Questions generated by an agent, spoken in your chosen language. Tap again to replay the question."
    },
    feat2_h: { es: "Respondes al habla", en: "You answer out loud" },
    feat2_p: {
      es: "Grabas tu respuesta y Whisper la transcribe. Puedes repetir la grabación las veces que necesites.",
      en: "Record your answer; Whisper turns it into text. Replay or re-record as many times as you like."
    },
    feat3_h: { es: "Te valoran al final", en: "You get scored at the end" },
    feat3_p: {
      es: "Al terminar, el agente te devuelve una evaluación con fortalezas y zonas de mejora.",
      en: "At the end, the agent returns a review with strengths and areas to improve."
    },
    feat4_h: { es: "Se abre abriendo el HTML", en: "Open the HTML, done" },
    feat4_p: {
      es: "Todo se ejecuta en tu navegador. Sin instalar nada; sin depender de internet para la demo.",
      en: "Everything runs in your browser. Nothing to install; the demo needs no internet."
    },

    how_head: { es: "Tres pasos. Nada más.", en: "Three steps. That's all." },
    how_lede: {
      es: "Un flujo pensado para sentirse como una entrevista de verdad, no como un formulario.",
      en: "A flow built to feel like a real interview, not a form."
    },
    how1_h: { es: "Elige idioma y empieza", en: "Pick a language and start" },
    how1_p: {
      es: "Castellano o inglés. Pulsa «Empezar entrevista» y listo.",
      en: "Spanish or English. Tap “Start interview” and you're in."
    },
    how2_h: { es: "Escucha, contesta, repite", en: "Listen, answer, replay" },
    how2_p: {
      es: "El entrevistador pregunta, tú respondes al habla. Si quieres escuchar la pregunta otra vez, hay un botón para reproducirla.",
      en: "The interviewer asks; you answer out loud. Want to hear the question again? One button replays it."
    },
    how3_h: { es: "Recibe tu evaluación", en: "Get your verdict" },
    how3_p: {
      es: "Al cierre, el agente te da un veredicto con fortalezas y sugerencias concretas.",
      en: "At the close, the agent gives you a verdict with strengths and concrete suggestions."
    },

    setup_head: { es: "Dos modos, a tu manera", en: "Two modes, your way" },
    setup_lede: {
      es: "Listo para usar tal cual. O conectado a Whisper y a un modelo propio si lo prefieres.",
      en: "Ready to use as-is — or wired to Whisper and your own model if you prefer."
    },
    setup1_h: { es: "Modo demo (sin clave)", en: "Demo mode (no key)" },
    setup1_p: {
      es: "Un entrevistador interno encadena la sesión con preguntas preparadas y usa la voz del navegador. Funciona sin conexión ni claves.",
      en: "A built-in interviewer drives the session with prepared questions using your browser's voice. Works offline, no keys."
    },
    setup2_h: { es: "Modo Whisper + LLM", en: "Whisper + LLM mode" },
    setup2_p: {
      es: "En «Configuración», apunta al servidor local de llama.cpp / whisper.cpp. Funciona con cualquier modelo GGUF pequeño de la máquina.",
      en: "In “Settings”, point at your local llama.cpp / whisper.cpp server. Works with any small GGUF model on this machine."
    },

    foot_copy: {
      es: "VERBATIM · simulador de entrevistas por voz — hecho para practicar, sin servidores.",
      en: "VERBATIM · voice interview simulator — made to practice, with no servers."
    },

    /* ---------------- Interview session ---------------- */
    room_title: {
      es: "Simulador de entrevistas",
      en: "Interview Simulator"
    },
    room_lede: {
      es: "Habla como lo haría en una entrevista real. El agente te hace las preguntas y valora tus respuestas.",
      en: "Speak as you would in a real interview. The agent asks and scores your answers."
    },
    role_agent: { es: "Entrevistador", en: "Interviewer" },
    role_you: { es: "Tú", en: "You" },

    status_idle: { es: "A la espera", en: "Ready" },
    status_agent_speaking: { es: "Preguntando", en: "Asking" },
    status_listening: { es: "Grabando", en: "Recording" },
    status_thinking: { es: "Analizando", en: "Analyzing" },
    status_done: { es: "Finalizado", en: "Done" },

    btn_record: { es: "Grabar respuesta", en: "Record answer" },
    btn_stop: { es: "Parar", en: "Stop" },
    btn_replay: { es: "Reproducir pregunta", en: "Replay question" },
    btn_hide_transcript: { es: "Ocultar transcripción", en: "Hide transcript" },
    btn_show_transcript: { es: "Mostrar transcripción", en: "Show transcript" },
    btn_rerecord: { es: "Volver a grabar", en: "Re-record" },
    btn_end: { es: "Terminar entrevista", en: "End interview" },
    btn_retry: { es: "Nueva entrevista", en: "New interview" },

    prompt_waiting: {
      es: "Pulsa el micrófono cuando estés listo para empezar.",
      en: "Tap the microphone when you're ready to begin."
    },
    prompt_asked: {
      es: "Has oído la pregunta. Pulsa para responder.",
      en: "You heard the question. Tap to answer."
    },
    prompt_recording: {
      es: "Estás grabando… habla con naturalidad.",
      en: "Recording… speak naturally."
    },
    prompt_thinking: {
      es: "El agente está procesando tu respuesta.",
      en: "The agent is processing your answer."
    },
    prompt_finished: {
      es: "Has terminado tus respuestas. Pulsa «Terminar» para recibir tu evaluación.",
      en: "You've answered everything. Tap “End” to get your review."
    },

    verdict_title: { es: "Tu evaluación", en: "Your evaluation" },
    verdict_score_label: { es: " puntuación", en: " score" },
    verdict_grade: { es: "Nivel alto", en: "Strong showing" },
    note_strengths_h: { es: "Fortalezas", en: "Strengths" },
    note_improve_h: { es: "A mejorar", en: "To improve" },
    note_next_h: { es: "Sugerencia siguiente", en: "Next step" },

    settings_title: { es: "Configuración", en: "Settings" },
    s_stt_engine: { es: "Motor de transcripción (STT)", en: "Transcription engine (STT)" },
    s_tts_engine: { es: "Voz del entrevistador (TTS)", en: "Interviewer voice (TTS)" },
    s_agent_engine: { es: "Agente entrevistador", en: "Interviewer agent" },
    s_whisper_url: { es: "Endpoint Whisper (transcripción)", en: "Whisper endpoint (transcription)" },
    s_llm_url: { es: "Agent LLM (chat completions)", en: "Agent LLM (chat completions)" },
    s_api_key: { es: "Clave API", en: "API key" },
    s_voice: { es: "Voz TTS", en: "TTS voice" },
    s_save: { es: "Guardar", en: "Save" },
    s_saved: { es: "Guardado", en: "Saved" },
    s_hint_demo: {
      es: "Sin ninguna clave, la demo usa el entrevistador interno y la voz del navegador.",
      en: "With no keys set, the demo uses the built-in interviewer and browser voice."
    },
    s_hint_remote: {
      es: "Servidores locales compatibles con OpenAI (/inference y /v1/chat/completions): whisper.cpp (puerto 8081) y llama-server (puerto 8080). Apunta también a cualquier proveedor cloud.",
      en: "Local OpenAI-compatible servers (/inference and /v1/chat/completions): whisper.cpp (port 8081) and llama-server (port 8080). Also works with any cloud provider."
    },
    s_whisper_hint: {
      es: "Necesitas un servidor whisper.cpp corriendo (ej. bash scripts/run-whisper.sh) antes de transcribir. El modelo es ~/.local/share/verbatim/models/ggml-small.bin; el endpoint es http://localhost:8081/inference.",
      en: "You need a whisper.cpp server running (e.g. bash scripts/run-whisper.sh) before transcription. Model is ~/.local/share/verbatim/models/ggml-small.bin; the endpoint is http://localhost:8081/inference."
    },
    s_whisper_status_down: {
      es: "El servidor de Whisper no está corriendo. Ábrelo desde la terminal:",
      en: "The whisper server isn't running. Launch it from your terminal:"
    },
    s_whisper_status_up: {
      es: "Servidor Whisper detectado ✓ — ya puedes transcribir.",
      en: "Whisper server detected ✓ — you can transcribe now."
    },
    s_copy_launch: { es: "Copiar comando", en: "Copy command" },
    s_copied: { es: "✓ Copiado", en: "✓ Copied" },
    s_start_hint: {
      es: "Una vez ejecutado, esta tarjeta pasa a detectar el servidor automáticamente.",
      en: "Once run, this card will auto-detect the server and you can close it."
    },
    s_mic_input: { es: "Micrófono de entrada", en: "Input microphone" },
    s_mic_default: { es: "Micrófono por defecto (sistema)", en: "System default microphone" },
    s_mic_default_name: { es: "Micrófono por defecto (sistema) — {name}", en: "System default microphone — {name}" },
    s_mic_default_tag: { es: "por defecto", en: "default" },
    s_mic_in_use: { es: "en uso", en: "in use" },
    s_mic_generic: { es: "Micrófono", en: "Microphone" },
    s_mic_hint: {
      es: "Se aplica a la grabación con Whisper. La «voz del navegador» usa siempre el micrófono por defecto del sistema.",
      en: "Applies to Whisper recording. Browser speech always uses the system default microphone."
    },
    s_agent_status_down: {
      es: "El servidor del agente no está corriendo. Ábrelo desde la terminal:",
      en: "The agent server isn't running. Launch it from your terminal:"
    },
    s_agent_status_up: {
      es: "Servidor del agente detectado — modelo cargado:",
      en: "Agent server detected — model loaded:"
    },

    s_mic_test: { es: "Probar micro", en: "Test mic" },
    s_mic_diag: { es: "Diagnóstico", en: "Diagnose" },
    s_mic_test_rec: { es: "Grabando 3 s… habla ahora", en: "Recording 3 s… speak now" },
    s_mic_test_ok: { es: "Micrófono OK", en: "Mic OK" },
    s_mic_test_low: {
      es: "Nivel muy bajo: revisa el micrófono elegido o el volumen de entrada del sistema.",
      en: "Very low level: check the chosen mic or the system input volume."
    },
    s_tts_piper_hint: {
      es: "Piper es una red neuronal local: arráncalo con bash scripts/run-piper.sh (puerto 8082). La voz del navegador usa las voces del sistema.",
      en: "Piper is a local neural network: start it with bash scripts/run-piper.sh (port 8082). The browser voice uses system voices."
    },
    err_tts_piper: {
      es: "No se pudo usar Piper; uso la voz del navegador.",
      en: "Couldn't reach Piper; using the browser voice."
    },

    err_no_mic: {
      es: "No se pudo acceder al micrófono. Permite el acceso e inténtalo de nuevo.",
      en: "Microphone access was denied. Allow microphone access and try again."
    },
    err_mic_busy: {
      es: "El micrófono está en uso por otra aplicación. Ciérrala e inténtalo de nuevo.",
      en: "The microphone is in use by another application. Close it and try again."
    },
    err_mic_missing: {
      es: "No se ha detectado ningún micrófono. Conecta uno e inténtalo de nuevo.",
      en: "No microphone found. Connect one and try again."
    },
    err_mic_stale: {
      es: "El micrófono guardado ya no existe (el sistema cambió los dispositivos). Se usará el micrófono por defecto.",
      en: "The saved microphone no longer exists (the system changed devices). Falling back to the system default."
    },
    err_mic_monitor: {
      es: "El micrófono guardado era un «monitor» de salida del sistema, no un micrófono: grababa silencio. Se usará el micrófono por defecto.",
      en: "The saved microphone was a system output \"monitor\", not a mic: it recorded silence. Falling back to the system default."
    },
    err_mic_lost: {
      es: "La captura del micrófono se ha interrumpido: otra app lo ha tomado o se ha desconectado.",
      en: "Microphone capture was interrupted: another app took it or it was unplugged."
    },
    err_stt_convert: {
      es: "No se pudo convertir el audio a WAV; se envía el formato original.",
      en: "Couldn't convert audio to WAV; sending the original format."
    },
    err_stt_failed: {
      es: "No se pudo transcribir. Comprueba que el servidor de Whisper esté corriendo.",
      en: "Transcription failed. Check that the Whisper server is running."
    },
    err_stt_empty: {
      es: "No se ha detectado voz en la grabación. Habla más cerca del micrófono.",
      en: "No speech detected in the recording. Speak closer to the microphone."
    },
    err_mic_silence: {
      es: "La grabación llega casi vacía (nivel muy bajo): revisa el micrófono elegido en ⚙️ o sube el volumen de entrada del sistema.",
      en: "The recording arrives nearly empty (very low level): check the microphone chosen in ⚙️ or raise the system input volume."
    },
    err_tts_novoice: {
      es: "Sin voces del sistema: la voz del entrevistador no sonará. Instala/activa speech-dispatcher (Linux) o elige una voz en ⚙️.",
      en: "No system voices: the interviewer will be silent. Install/enable speech-dispatcher (Linux) or pick a voice in ⚙️."
    },
    err_tts_failed: {
      es: "Fallo de síntesis de voz",
      en: "Speech synthesis failed"
    },
    s_answer_empty: {
      es: "— sin audio detectado —",
      en: "— no audio detected —"
    },
    review_loading: {
      es: "Analizando tu respuesta…",
      en: "Analyzing your answer…"
    },
    review_error: {
      es: "No se pudo analizar la respuesta.",
      en: "Couldn't analyze the answer."
    },
    cat_grammar: { es: "Gramática", en: "Grammar" },
    cat_vocab: { es: "Vocabulario", en: "Vocabulary" },
    cat_concept: { es: "Concepto", en: "Concept" },
    coach_title: { es: "Coach", en: "Coach" },
    coach_waiting: {
      es: "Cuando el entrevistador haga una pregunta, aquí verás dos posibles respuestas.",
      en: "When the interviewer asks a question, you'll see two possible answers here."
    },
    coach_thinking: {
      es: "Pensando posibles respuestas…",
      en: "Thinking of possible answers…"
    },
    coach_cv: { es: "Basada en tu CV", en: "Based on your CV" },
    coach_general: { es: "Respuesta modelo", en: "Model answer" },
    btn_save_answer: { es: "Guardar resposta", en: "Save answer" },
    save_done: {
      es: "Guardat a {file} (pregunta + resposta del Coach).",
      en: "Saved to {file} (question + coach answers)."
    },
    save_saved_before: {
      es: "Aquesta pregunta ja estava guardada.",
      en: "This question was already saved."
    },
    coach_demo_hint: {
      es: "El coach necesita el Agente entrevistador en modo Local (⚙️ → Agente entrevistador).",
      en: "The coach needs the interviewer agent in Local mode (⚙️ → Interviewer agent)."
    },
    coach_error: {
      es: "El coach no pudo generar respuestas en este turno. Sigue con la entrevista.",
      en: "The coach couldn't generate answers this turn. Carry on with the interview."
    },
    topics_title: { es: "Temas", en: "Topics" },
    topics_hint: {
      es: "El entrevistador preguntará solo por los temas marcados. Con todo activo, la entrevista alterna lo personal, lo no técnico y lo técnico.",
      en: "The interviewer will only ask about the checked topics. With everything on, the interview mixes personal, non-technical and technical."
    },
    topics_intro_first: {
      es: "Empezar siempre con la presentación",
      en: "Always start with the self-intro"
    },
    s_folder_label: { es: "Carpeta de contexto", en: "Context folder" },
    s_folder_hint: {
      es: "Selecciona una carpeta con proyectos/repositorios para generar preguntas basadas en su contenido.",
      en: "Select a folder with projects/repositories to generate questions based on its content."
    },
    s_folder_loading: { es: "Cargando archivos…", en: "Loading files…" },
    s_folder_loaded: { es: "{count} archivos cargados ({size})", en: "{count} files loaded ({size})" },
    s_folder_empty: { es: "No se encontraron archivos de texto", en: "No text files found" },
    s_folder_error: { es: "Error al leer los archivos", en: "Error reading files" },
    s_folder_toast_ok: { es: "Contenido cargado desde {count} archivos", en: "Content loaded from {count} files" },
    s_folder_toast_empty: { es: "La carpeta no contiene archivos de texto reconocidos", en: "Folder contains no recognized text files" },
    s_folder_toast_err: { es: "Error al procesar la carpeta seleccionada", en: "Error processing selected folder" },
    s_tts_test: { es: "Probar voz", en: "Test voice" },
    tts_test_phrase: {
      es: "Hola. Soy tu entrevistador. Así sonaré durante la sesión.",
      en: "Hi. I'm your interviewer. This is how I'll sound during the session."
    },
    err_not_supported: {
      es: "Este navegador no soya grabación de voz. Usa Chrome/Edge/Firefox actualizado.",
      en: "This browser can't record voice. Use a recent Chrome, Edge or Firefox."
    }
  };

  /* ---------------- helpers ---------------- */
  const STORE_KEY = "verbatim.locale";
  const defaults = { agent: "agent", stt: "whisper" };

  function getLocale() {
    let l = localStorage.getItem(STORE_KEY);
    if (!l) {
      l = navigator.language && navigator.language.toLowerCase().startsWith("en") ? "en" : "es";
    }
    return l;
  }
  function apply(locale) {
    document.documentElement.lang = locale;
    document.querySelectorAll("[data-i18n]").forEach(function (el) {
      const key = el.getAttribute("data-i18n");
      if (STRINGS[key]) el.innerHTML = STRINGS[key][locale];
    });
    document.querySelectorAll(".lang-switch [data-lang]").forEach(function (b) {
      b.setAttribute("aria-selected", String(b.getAttribute("data-lang") === locale));
    });
  }

  function setLocale(locale) {
    if (locale !== "es" && locale !== "en") return;
    localStorage.setItem(STORE_KEY, locale);
    apply(locale);
    // reflect in any status copy that depends on language at runtime
    if (window.VERBATIM && typeof window.VERBATIM.setLocale === "function") {
      window.VERBATIM.setLocale(locale);
    }
  }

  /* wire the global language switchers */
  function wireSwitch() {
    document.querySelectorAll(".lang-switch [data-lang]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        setLocale(btn.getAttribute("data-lang"));
      });
    });
  }

  function init() {
    apply(getLocale());
    wireSwitch();
    window.I18N = {
      get: function (k) { return STRINGS[k] ? (STRINGS[k][getLocale()] || "") : ""; },
      set: setLocale,
      getLocale: getLocale
    };
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else { init(); }

  window.I18N_STRINGS = STRINGS;
})();
