/* == generated by scripts/build-offer-sets.py — DO NOT EDIT ==
   Source of truth: apply/sets/<empresa>.json (outside this repo).
   Rebuild: python3 scripts/build-offer-sets.py */
(function () {
  "use strict";
  window.OFFER_SETS = {
  "back_market": {
    "brief": {
      "en": "Back Market: refurbished-goods marketplace, B Corp 93.2, Barcelona hybrid 3 days. Six-stage process (HR screen 45', coding test 60', system design 60', data module 45', tech leadership + manager 75', BM values 45'). Stated challenge: migrating the monolith to a distributed service architecture and raising engineering standards. Stack: Python, FastAPI, SQLAlchemy, Celery, PostgreSQL, Redis, Kafka, RabbitMQ, GCP, Datadog, ArgoCD; frontend Vue/Nuxt/TypeScript.",
      "es": "Back Market: marketplace de recondicionado, B Corp 93.2, Barcelona híbrido 3 días. Proceso de 6 fases (HR screen 45', coding test 60', system design 60', data module 45', tech leadership + manager 75', BM values 45'). Reto declarado: migrar el monolito a una arquitectura distribuida de servicios y subir los estándares de ingeniería. Stack: Python, FastAPI, SQLAlchemy, Celery, PostgreSQL, Redis, Kafka, RabbitMQ, GCP, Datadog, ArgoCD; frontend Vue/Nuxt/TypeScript."
    },
    "company": "Back Market",
    "gaps": [
      {
        "probe": {
          "en": "Task-queue semantics: @app.task, routing, acks_late, worker idempotency, retries with backoff, poison messages to DLQ. Map it to your own RabbitMQ consumer + DLT (kafka-adapter-telemetry): the same problem without the framework.",
          "es": "Semántica de cola de tareas: @app.task, routing, acks_late, idempotencia del worker, retries con backoff, poison messages a DLQ. Mapear con el consumidor RabbitMQ + DLT propio (kafka-adapter-telemetry): el mismo problema sin el framework."
        },
        "topic": "Celery"
      },
      {
        "probe": {
          "en": "PG specifics versus Oracle/MySQL: JSONB, arrays, CTEs (WITH), ON CONFLICT (upsert), partial indexes, EXPLAIN ANALYZE; modeling and normalization trade-offs; BigQuery as the columnar destination (Snowflake concept).",
          "es": "Especificidades PG frente a Oracle/MySQL: JSONB, arrays, CTEs WITH, ON CONFLICT (upsert), índices parciales, EXPLAIN ANALYZE; modelado y trade-offs de normalización; BigQuery como destino columnar (concepto Snowflake)."
        },
        "topic": "PostgreSQL"
      },
      {
        "probe": {
          "en": "Likely scenario: a service with its own database, release schedule and SLAs. Template: API contract (OpenAPI) → database per service (no shared DB) → events for sync (outbox) → idempotency → observability (metrics, traces, alerts) → migration/rollback. Tie-in: the multi-country Open Gateway adapters as lived experience.",
          "es": "Escenario probable: servicio con BD propia, release schedule y SLAs. Plantilla: contrato API (OpenAPI) → BD por servicio (no shared DB) → eventos para sincronizar (outbox) → idempotencia → observabilidad (métricas, trazas, alertas) → migración/rollback. Tie-in: adaptadores Open Gateway multipaís como caso vivido."
        },
        "topic": "System design"
      },
      {
        "probe": {
          "en": "Declared weak point in the cover letter: TS/Next/Astro yes, Vue no. Viable minimum: SFC, reactivity, router, Pinia state, Next vs Nuxt comparison — to speak with ownership, not to oversell.",
          "es": "Punto débil declarado en la carta: TS/Next/Astro sí, Vue no. Mínimo viable: SFC, reactividad, router, estado con Pinia, comparativa Next vs Nuxt — para hablar con propiedad, no para vender experiencia."
        },
        "topic": "Vue/Nuxt"
      },
      {
        "probe": {
          "en": "Transferable concepts from AWS/Kibana/Jenkins-GH Actions: vocabulary, not depth. Don't study deeply; know how to translate what you already operate.",
          "es": "Conceptos transferibles desde AWS/Kibana/Jenkins-GH Actions: vocabulario, no profundidad. No estudiar a fondo; saber traducir lo que ya operas."
        },
        "topic": "GCP / Datadog / ArgoCD"
      }
    ],
    "id": "back_market",
    "role": {
      "en": "Experienced Software Engineer, Backend — Code Foundations (Senior I)",
      "es": "Experienced Software Engineer, Backend — Code Foundations (Senior I)"
    },
    "stages": [
      {
        "focus": {
          "en": "Spoken English (the Affirm lesson: record yourself and listen before), motivation for the reuse mission and the monolith-to-services transition, and logistics (salary band, hybrid days, squad).",
          "es": "Inglés hablado (la lección Affirm: grabarse y escucharse antes), motivación por la misión reúso y la transición monolito→servicios, y logística (banda salarial, días híbridos, squad)."
        },
        "id": "hr_screen",
        "label": {
          "en": "HR screen (45')",
          "es": "HR screen (45')"
        },
        "questions": [
          {
            "en": "Introduce yourself in one minute: your background and what draws you to Back Market.",
            "es": "Preséntate en un minuto: trayectoria y qué te atrae de Back Market."
          },
          {
            "en": "What attracts you to our reuse mission and to the monolith-to-services transition ahead of us?",
            "es": "¿Qué te atrae de nuestra misión de reuso y de la transición de monolito a servicios que tenemos por delante?"
          },
          {
            "en": "Tell me how you have built and standardized backend platforms for other teams.",
            "es": "Cuéntame cómo has construido y estandarizado plataformas de backend para otros equipos."
          },
          {
            "en": "What is your English like day to day: meetings, technical decisions, writing?",
            "es": "¿Cómo es tu inglés en el día a día: reuniones, decisiones técnicas, escritura?"
          },
          {
            "en": "What are your salary expectations for this level in Barcelona?",
            "es": "¿Cuáles son tus expectativas salariales para este nivel en Barcelona?"
          }
        ]
      },
      {
        "focus": {
          "en": "Async Python (FastAPI + SQLAlchemy AsyncSession) and task queues: Celery seen from what you already master (RabbitMQ, DLT, idempotency, retries).",
          "es": "Python asíncrono (FastAPI + SQLAlchemy AsyncSession) y colas de tareas: Celery visto desde lo que ya dominas (RabbitMQ, DLT, idempotencia, retries)."
        },
        "id": "coding_test",
        "label": {
          "en": "Coding test (60')",
          "es": "Coding test (60')"
        },
        "questions": [
          {
            "en": "What is Celery, and how does it compare to the RabbitMQ consumer with a dead-letter queue you built in your telemetry pipeline?",
            "es": "¿Qué es Celery y en qué se parece y difiere del consumidor RabbitMQ con cola de muertos que construiste en tu pipeline de telemetría?"
          },
          {
            "en": "How would you design a Celery task to be idempotent and retry-safe?",
            "es": "¿Cómo diseñarías una tarea de Celery para que sea idempotente y segura ante reintentos?"
          },
          {
            "en": "Explain acks_late: what happens if the worker dies mid-task with early acknowledgements versus acks_late?",
            "es": "Explica acks_late: ¿qué ocurre si el worker cae a mitad de tarea con acknowledgements tempranos y con acks_late?"
          },
          {
            "en": "A poison message is blocking the queue: how do you detect it and how do you mitigate it?",
            "es": "Un mensaje envenenado bloquea la cola: ¿cómo lo detectas y cómo lo mitigas?"
          },
          {
            "en": "How do you structure an async FastAPI endpoint with SQLAlchemy AsyncSession: sessions, transactions and error handling?",
            "es": "¿Cómo estructuras un endpoint FastAPI async con SQLAlchemy AsyncSession: sesiones, transacciones y errores?"
          }
        ]
      },
      {
        "focus": {
          "en": "Design a service with its own database, release schedule and SLAs: contract, outbox, idempotency, observability, migration with rollback. Anchor on the Open Gateway adapters (~90, 4 countries).",
          "es": "Diseño de un servicio con BD propia, release schedule y SLAs: contrato, outbox, idempotencia, observabilidad, migración con rollback. Anclar en los adaptadores Open Gateway (~90, 4 países)."
        },
        "id": "system_design",
        "label": {
          "en": "System design (60')",
          "es": "System design (60')"
        },
        "questions": [
          {
            "en": "Design a pricing service that serves prices to the storefront: API contract, its own database, synchronization and SLAs.",
            "es": "Diseña un servicio de pricing que sirva precios a la tienda: contrato de API, base de datos propia, sincronización y SLAs."
          },
          {
            "en": "How do you synchronize data across services without coupling them? Explain the outbox pattern and its relationship with idempotency.",
            "es": "¿Cómo sincronizas datos entre servicios sin acoplarlos? Explica el patrón outbox y su relación con la idempotencia."
          },
          {
            "en": "You extract a domain from the monolith into a service: how do you migrate traffic without downtime and with a rollback plan?",
            "es": "Extraes un dominio del monolito a un servicio: ¿cómo migras el tráfico sin cortar el servicio y con plan de rollback?"
          },
          {
            "en": "How do you make a new service observable: metrics, traces, alerts and runbooks? What does 'run what you build' mean to you?",
            "es": "¿Cómo dejas un servicio nuevo observable: métricas, trazas, alertas y runbooks? ¿Qué significa para ti 'run what you build'?"
          },
          {
            "en": "What trade-offs did you learn operating close to 90 adapters across 4 countries, and how have they changed the way you design?",
            "es": "Qué trade-offs aprendiste operando cerca de 90 adaptadores en 4 países y cómo han cambiado tu forma de diseñar?"
          }
        ]
      },
      {
        "focus": {
          "en": "Concrete PostgreSQL: JSONB, CTEs, ON CONFLICT, partial indexes, EXPLAIN ANALYZE; modeling and trade-offs. Bridge: Snowflake ↔ BigQuery (columnar).",
          "es": "PostgreSQL concreto: JSONB, CTEs, ON CONFLICT, índices parciales, EXPLAIN ANALYZE; modelado y trade-offs. Puente: Snowflake ↔ BigQuery (columnar)."
        },
        "id": "data_module",
        "label": {
          "en": "Data module (45')",
          "es": "Data module (45')"
        },
        "questions": [
          {
            "en": "When would you choose JSONB in PostgreSQL and what does it cost you versus normalized columns?",
            "es": "¿Cuándo elegirías JSONB en PostgreSQL y qué te cuesta frente a columnas normalizadas?"
          },
          {
            "en": "Explain ON CONFLICT (upsert) and where you would have used it in your idempotent telemetry hub.",
            "es": "Explica ON CONFLICT (upsert) y dónde lo habrías usado en tu hub idempotente de telemetría."
          },
          {
            "en": "A query is slow in production: what does EXPLAIN ANALYZE tell you and what do you do from there?",
            "es": "Una consulta va lenta en producción: ¿qué información te da EXPLAIN ANALYZE y qué haces a partir de ahí?"
          },
          {
            "en": "When do you reach for CTEs and window functions, and what pitfalls have you seen?",
            "es": "¿CuándoReachrecurres a CTEs y window functions y qué trampas has visto?"
          },
          {
            "en": "Model orders with their line items: normalization, indexes, and the justification for each decision.",
            "es": "Modela pedidos con sus líneas: normalización, índices y justificación de cada decisión."
          }
        ]
      },
      {
        "focus": {
          "en": "Stories in STAR format. Literal question from the ad: 'tell me about an architecture you made better for other engineers'. Prepared: CLI suite (operating standards for ~90 services) and harness-standard (specs + human gates).",
          "es": "Historias en formato STAR. Pregunta literal del anuncio: 'tell me about an architecture you made better for other engineers'. Preparadas: suite CLI (estándares de operación para ~90 servicios) y harness-standard (specs + human gates)."
        },
        "id": "tech_leadership",
        "label": {
          "en": "Tech leadership + manager (75')",
          "es": "Tech leadership + manager (75')"
        },
        "questions": [
          {
            "en": "Tell me about an architecture or tooling you made better for other engineers.",
            "es": "Cuéntame de una arquitectura o herramienta que mejoraste para otros ingenieros."
          },
          {
            "en": "How do you raise a team's quality bar without being their formal lead?",
            "es": "¿Cómo subes el nivel de calidad de un equipo sin ser su lead formal?"
          },
          {
            "en": "Tell me about a production incident with real impact and how you handled it.",
            "es": "Cuéntame un incidente de producción con impacto real y cómo lo llevaste."
          },
          {
            "en": "How do you document technical decisions so they outlive your time on the team?",
            "es": "¿Cómo documentas decisiones técnicas para que sobrevivan a tu paso por el equipo?"
          },
          {
            "en": "How have you onboarded junior engineers, and what of that has endured?",
            "es": "¿Cómo has hecho onboarding de ingenieros junior y qué ha sobrevivido de eso?"
          }
        ]
      },
      {
        "focus": {
          "en": "Three reasons for Back Market: reuse mission, FastAPI stack (zero gap), monolith-to-services transformation as the exact profile challenge. Read careers + engineering blog beforehand.",
          "es": "Tres razones por Back Market: misión reúso, stack FastAPI (cap gap), transformación monolito→servicios como el reto exacto del perfil. Leer careers + engineering blog antes."
        },
        "id": "values",
        "label": {
          "en": "BM values (45')",
          "es": "BM values (45')"
        },
        "questions": [
          {
            "en": "What do you know about our business model and what being a B Corp means?",
            "es": "¿Qué sabes de nuestro modelo de negocio y de lo que significa ser B Corp?"
          },
          {
            "en": "Why Back Market and not any of the other offers you have on the table?",
            "es": "¿Por qué Back Market y no cualquiera de las otras ofertas que tienes sobre la mesa?"
          },
          {
            "en": "How do you fit into a Barcelona hybrid team with three office days?",
            "es": "¿Cómo encajas en un equipo híbrido de Barcelona con three días presenciales?"
          },
          {
            "en": "Tell me about a technical decision you defended that turned out wrong: what did you do?",
            "es": "Cuéntame una decisión técnica que defendiste y que al final no salió bien: ¿qué hiciste?"
          }
        ]
      }
    ],
    "stories": [
      {
        "action": {
          "en": "API-by-API state audit, wave-based migration plan, traceability for every decision (ADRs), homogeneous conventions and two-way code reviews. Key line: 'the context changes; the standard does not'.",
          "es": "Auditoría de estado API a API, plan de migración por olas, trazabilidad de cada decisión (ADRs), convenciones homogéneas y revisiones bidireccionales. Frase clave: 'the context changes; the standard does not'."
        },
        "id": "monolith-to-services",
        "label": {
          "en": "Monolith → services (Mapfre, 39 APIs)",
          "es": "Monolito → servicios (Mapfre, 39 APIs)"
        },
        "result": {
          "en": "39 APIs modernized onto one stack with traceable decisions; the team can operate and evolve the whole without depending on me.",
          "es": "39 APIs modernizadas al mismo stack con decisiones trazables; el equipo puede operar y evolucionar el conjunto sin depender de mí."
        },
        "situation": {
          "en": "39 legacy corporate APIs, heterogeneous stack, technical debt and uneven standards across teams.",
          "es": "39 APIs corporativas heredadas, stack heterogéneo, deuda técnica y estándares desiguales entre equipos."
        },
        "task": {
          "en": "Analyze and drive the consolidation of the 39 APIs onto a single stack (Node.js 24) without breaking consumers.",
          "es": "Analizar y consolidar la modernización de las 39 APIs hacia un stack único (Node.js 24) sin romper consumidores."
        }
      },
      {
        "action": {
          "en": "Authored a suite of 12+ Python CLI tools: pre-deploy checks, deployment verification, state queries, documentation and diagrams generated in CI/CD.",
          "es": "Autoría de una suite de más de 12 herramientas CLI en Python: pre-deploy checks, verificación de despliegues, consultas de estado, documentación y diagramas generados en CI/CD."
        },
        "id": "run-what-you-build",
        "label": {
          "en": "Run what you build (CLI suite, Open Gateway)",
          "es": "Run what you build (suite CLI, Open Gateway)"
        },
        "result": {
          "en": "~90 adapters in 4 countries operated through the same suite; systematic post-deploy verification and documentation that stays alive instead of rotting in a wiki.",
          "es": "~90 adaptadores en 4 países operados con la misma suite; verificación post-despliegue sistemática y documentación siempre viva en lugar de wikis obsoletas."
        },
        "situation": {
          "en": "Telefónica Open Gateway: ~90 REST adapters across 4 countries and 5-6 environments, operated by hand with repetitive mistakes.",
          "es": "Telefónica Open Gateway: ~90 adaptadores REST en 4 países y 5-6 entornos, operados a mano con errores repetitivos."
        },
        "task": {
          "en": "Cut operational errors and make the deploy-verify cycle repeatable without blocking the teams.",
          "es": "Reducir el error operativo y hacer repetible el ciclo desplegar-verificar sin bloquear a los equipos."
        }
      },
      {
        "action": {
          "en": "TDD + strict mypy + CI on md-mermaid-pdf; on CodebaseRAG, a golden set of 40+ Q/A pairs and an eval gate in CI with a committed baseline (recall@5 0.409 as the reference).",
          "es": "TDD + mypy strict + CI en md-mermaid-pdf; en CodebaseRAG, golden set de más de 40 preguntas/respuestas y un eval gate en CI con baseline committed (recall@5 0.409 como referencia)."
        },
        "id": "quality-gates",
        "label": {
          "en": "Quality gates (md-mermaid-pdf + CodebaseRAG)",
          "es": "Quality gates (md-mermaid-pdf + CodebaseRAG)"
        },
        "result": {
          "en": "Quality regressions caught in CI before release; the recall baseline makes any RAG degradation visible.",
          "es": "Regresiones de calidad atrapadas en CI antes de publicar; el baseline de recall hace visible cualquier degradación del RAG."
        },
        "situation": {
          "en": "Two personal projects where quality cannot rely on memory: a public CLI (md-mermaid-pdf) and a repository RAG (CodebaseRAG).",
          "es": "Dos proyectos personales donde la calidad no puede depender de memoria: una CLI pública (md-mermaid-pdf) y un RAG sobre repositorios (CodebaseRAG)."
        },
        "task": {
          "en": "Make every change prove by itself that it breaks nothing — and make it impossible for an LLM to degrade answers unnoticed.",
          "es": "Que cada cambio demuestre por sí mismo que no rompe nada — y que un LLM no pueda degradar las respuestas sin que se note."
        }
      },
      {
        "action": {
          "en": "Systematic root-cause analysis, reproduce before touching, fix with regression tests, and clear communication of impact to the client.",
          "es": "Root-cause analysis sistemático, reproducir antes de tocar, fix con pruebas de regresión y comunicación clara del impacto al cliente."
        },
        "id": "incidents-with-a-price",
        "label": {
          "en": "Incidents with a price tag (Zitro)",
          "es": "Incidentes con precio real (Zitro)"
        },
        "result": {
          "en": "Incidents resolved with documented root causes; fewer repeat failures and client trust preserved in money-sensitive operations.",
          "es": "Incidentes resueltos con causa raíz documentada; menos reincidencias y confianza del cliente mantenida en operaciones sensibles a dinero."
        },
        "situation": {
          "en": "Java server for the betting engine with online-casino integrations: a production failure touches real operator money.",
          "es": "Servidor Java del motor de apuestas con integraciones a casinos online: un fallo en producción afecta a dinero real de operadores."
        },
        "task": {
          "en": "Diagnose and resolve incidents under client pressure with no possibility of pausing the system.",
          "es": "Diagnosticar y resolver incidentes con presión de cliente y sin poder pausar el sistema."
        }
      },
      {
        "action": {
          "en": "Idempotent Oracle persistence, per-episode alerts (3 consecutive DOWN → 1 alert), DLT with retries, Testcontainers + EmbeddedKafka, README and 3 ADRs in English, e2e demo from scratch (demo.sh).",
          "es": "Persistencia idempotente en Oracle, alertas por episodio (3 DOWN consecutivos → 1 alerta), DLT con retries, Testcontainers + EmbeddedKafka, README y 3 ADRs en inglés, demo e2e desde cero (demo.sh)."
        },
        "id": "greenfield-end-to-end",
        "label": {
          "en": "Greenfield end-to-end (kafka-adapter-telemetry)",
          "es": "Greenfield end-to-end (kafka-adapter-telemetry)"
        },
        "result": {
          "en": "Complete and verified project: the e2e demo repeats idempotency by count, one alert per episode and DLT with corrupt JSON — a demonstrable method in interviews.",
          "es": "Proyecto completo y verificado: demo e2e repite idempotencia por recuento, una alerta por episodio y DLT con JSON corrupto — método demostrable en entrevista."
        },
        "situation": {
          "en": "No system existed: design from scratch an adapter telemetry pipeline (gateway → Kafka → hub → Oracle) as a personal project.",
          "es": "Ningún sistema: diseñar de cero un pipeline de telemetría de adaptadores (gateway → Kafka → hub → Oracle) como proyecto propio."
        },
        "task": {
          "en": "Apply the full standard — SDD with specs, ADRs, hexagonal per service, tests first — as a demonstration of method, not only of outcome.",
          "es": "Aplicar el estándar completo — SDD con specs, ADRs, hexagonal por servicio, tests primero — como demostración de método, no solo de resultado."
        }
      }
    ]
  },
  "clarivate": {
    "brief": {
      "en": "Clarivate (LS&H — Life Sciences & Healthcare): a family of Lead roles in an AI Engineering team (EM + 3 Lead SWE). Python backend (APIs, microservices, ETL) on Azure/AWS + LLM/agentic apps with reliability. Requirements: 7+ years, 4+ Python, 5+ cross-functional teams, 3+ years LLM/agentic (the flank to reposition: ~1.5 years of real depth, but treating LLMs as production systems).",
      "es": "Clarivate (LS&H — Life Sciences & Healthcare): familia de roles Lead en un equipo de AI Engineering (EM + 3 Lead SWE). Backend Python (APIs, microservicios, ETL) en Azure/AWS + LLM/agentic apps con fiabilidad. Requisitos: 7+ años, 4+ Python, 5+ equipos cross-functional, 3+ años LLM/agentic (el flanco a reposicionar: profundidad real ~1,5 años, pero tratando LLMs como sistemas de producción)."
    },
    "company": "Clarivate",
    "gaps": [
      {
        "probe": {
          "en": "No lying: less time, but the part that counts — quality gates, golden sets, committed baselines, specs with human gates. 'What makes an LLM a system, not a demo'.",
          "es": "No se miente: menos tiempo pero con lo que cuenta — gates de calidad, golden sets, baselines committed, specs con human gates. 'Lo que hace que un LLM sea un sistema y no una demo'."
        },
        "topic": "3+ años LLM/agentic (reposicionamiento)"
      },
      {
        "probe": {
          "en": "Zero Azure, solid AWS (Lambda, CDK, CloudFormation), and the offer accepts either. Translate concepts: resource groups≈accounts/CDK stacks, Azure AI Search≈managed vector store.",
          "es": "Cero Azure, AWS sólido (Lambda, CDK, CloudFormation) y la oferta acepta una u otra. Traducir conceptos: resource groups≈accounts/CDK stacks, Azure AI Search≈vector store gestionado."
        },
        "topic": "Azure"
      },
      {
        "probe": {
          "en": "Mentorship and standards are covered; multi-team influence is what needs defending with precedents: Mapfre governance (39 APIs) and the operations suite as standards others adopted.",
          "es": "Mentoría y estándares sobran; influencia multi-equipo es lo que hay que defender con precedentes: governance de Mapfre (39 APIs) y la suite de operación como estándares adoptados por otros."
        },
        "topic": "Influencia multi-equipo (nivel Lead)"
      },
      {
        "probe": {
          "en": "Real decisions documented in ADRs: pgvector vs Qdrant (ADR-0004), local mini-LLM with llama.cpp, nomic embeddings — cost, privacy and control trade-offs.",
          "es": "Decisiones reales documentadas en ADRs: pgvector vs Qdrant (ADR-0004), mini-LLM local con llama.cpp, embeddings nomic — trade-offs de coste, privacidad y control."
        },
        "topic": "Decisiones AI: in-house vs cloud vs open-source"
      }
    ],
    "id": "clarivate",
    "role": {
      "en": "Lead Software Engineer — AI Product Development (Barcelona, hybrid)",
      "es": "Lead Software Engineer — AI Product Development (Barcelona, híbrido)"
    },
    "stages": [
      {
        "focus": {
          "en": "Salary band (ask for it first), hybrid days, which LS&H product. Desired compensation: 78-85k base, flexible on total package; never the current salary.",
          "es": "Banda salarial (pedirla tú primero), días híbridos, qué producto LS&H. Compensación deseada: 78-85k base con flexibilidad por paquete; nunca el sueldo actual."
        },
        "id": "screen",
        "label": {
          "en": "Screen (compensation + fit)",
          "es": "Screen (compensación + encaje)"
        },
        "questions": [
          {
            "en": "Walk me through your background and what interests you about a Lead role in AI Product Development.",
            "es": "Cuéntame tu trayectoria y qué te interesa de un rol Lead en AI Product Development."
          },
          {
            "en": "What is your experience with LLMs in production?",
            "es": "¿Cuál es tu experiencia con LLMs en producción?"
          },
          {
            "en": "What are your compensation expectations for this role?",
            "es": "¿Cuáles son tus expectativas de compensación para este rol?"
          },
          {
            "en": "How have you led technically without being a formal manager?",
            "es": "¿Cómo has liderado técnicamente sin ser manager formal?"
          }
        ]
      },
      {
        "focus": {
          "en": "The differentiator: evals in CI, golden sets, committed baseline (CodebaseRAG: recall@5 0.409, 40+ Q/A), specs + human gates (harness-standard). The eval-baseline demo is ready to show live.",
          "es": "El diferenciador: evals en CI, golden sets, baseline committed (CodebaseRAG: recall@5 0.409, 40+ Q/A), specs + human gates (harness-standard). Demo del eval baseline lista para enseñar en vivo."
        },
        "id": "llm_reliability",
        "label": {
          "en": "Technical: LLM/agentic reliability",
          "es": "Técnico: fiabilidad LLM/agentic"
        },
        "questions": [
          {
            "en": "How do you know your LLM app hasn't gotten worse after a change?",
            "es": "¿Cómo sabes que tu app de LLM no ha empeorado después de un cambio?"
          },
          {
            "en": "Explain your eval baseline: what it measures, on which dataset, and what happens when it fails.",
            "es": "Explica tu eval baseline: qué mides, con qué dataset y qué pasa si falla."
          },
          {
            "en": "How do you decide between in-house, cloud API and open-source for an LLM component?",
            "es": "¿Cómo decides entre in-house, cloud API y open-source para un componente de LLM?"
          },
          {
            "en": "What does 'treating an LLM as a production system' mean versus 'just prompting'?",
            "es": "Qué significa 'tratar un LLM como un sistema de producción' frente a 'hacer prompting'?"
          },
          {
            "en": "How do you gate a coding agent's work before it reaches main?",
            "es": "¿Cómo gated el trabajo de un agente de código antes de llegar a main?"
          }
        ]
      },
      {
        "focus": {
          "en": "Idempotent Kafka gateway+hub with DLT and retries (kafka-adapter-telemetry), Snowflake/Cassandra/BigQuery, ETL on Azure/AWS. Idempotency-by-count as the demonstration.",
          "es": "Kafka gateway+hub idempotente con DLT y retries (kafka-adapter-telemetry), Snowflake/Cassandra/BigQuery, ETL a Azure/AWS. Idempotencia por recuento como demostración."
        },
        "id": "data_pipelines",
        "label": {
          "en": "Technical: data pipelines",
          "es": "Técnico: pipelines de datos"
        },
        "questions": [
          {
            "en": "Design a pipeline that persists telemetry events without duplicates even when the producer retries.",
            "es": "Diseña un pipeline que persista eventos de telemetría sin duplicados aunque el productor reintente."
          },
          {
            "en": "What is a DLQ and how do you decide between retry, backoff and discard?",
            "es": "¿Qué es una DLT y cómo decides entre retry, backoff y descarte?"
          },
          {
            "en": "SQL versus NoSQL for historical data: when have you chosen each and why?",
            "es": "SQL vs NoSQL para históricos: ¿cuándo has elegido cada uno y por qué?"
          },
          {
            "en": "How would you shape an ETL on Azure given your experience is on AWS?",
            "es": "¿Cómo harías el patrón de un ETL a Azure si tu experiencia es AWS?"
          }
        ]
      },
      {
        "focus": {
          "en": "Scoping AI-platform initiatives and influencing technical direction. Precedents: governance of the 39-API modernization, the CLI suite adopted as a standard, harness-standard as a public methodology.",
          "es": "Scoping de iniciativas AI platform e influir en dirección técnica. Precedentes: governance de la modernización de 39 APIs, suite CLI adoptada como estándar, harness-standard como metodología pública."
        },
        "id": "lead_influence",
        "label": {
          "en": "Lead: influence and standards",
          "es": "Lead: influencia y estándares"
        },
        "questions": [
          {
            "en": "How have you influenced the technical direction of teams other than your own?",
            "es": "¿Cómo has influido en la dirección técnica de equipos que no son el tuyo?"
          },
          {
            "en": "Tell me how you standardized something and got the standard adopted without formal authority.",
            "es": "Cuéntame cómo estandarizaste algo y adoptaste el estándar sin autoridad formal."
          },
          {
            "en": "How do you scope an AI initiative when the initial scope is a hunch?",
            "es": "¿Cómo scopes una iniciativa AI cuando el alcance inicial es una corazonada?"
          },
          {
            "en": "How do you mentor senior engineers without micromanaging?",
            "es": "¿Cómo mentorizas a ingenieros senior sin microgestionar?"
          }
        ]
      }
    ],
    "stories": [
      {
        "action": {
          "en": "A 40+ Q/A golden set, a CI eval with a committed baseline (recall@5 0.409) and a gate: if recall drops, the change doesn't pass — like a unit test, but for semantic quality.",
          "es": "Golden set de 40+ Q/A, eval en CI con baseline committed (recall@5 0.409) y gate: si el recall cae, el cambio no pasa — igual que un test de unidad, pero de calidad semántica."
        },
        "id": "llm-reliability",
        "label": {
          "en": "LLM reliability (CodebaseRAG)",
          "es": "Fiabilidad de LLMs (CodebaseRAG)"
        },
        "result": {
          "en": "LLM changes are accepted on evidence; the baseline makes any degradation visible. That's the answer to '3 years of LLM': less time, but the time that counts.",
          "es": "Los cambios de LLM se aceptan por evidencia; el baseline hace visible cualquier degradación. Es la respuesta a '3 años de LLM': menos tiempo, pero el que cuenta."
        },
        "situation": {
          "en": "A repository RAG where every prompt or retrieval change could silently degrade answers.",
          "es": "Un RAG sobre repositorios donde cada cambio de prompt o retrieval podía degradar las respuestas sin que nadie lo notara."
        },
        "task": {
          "en": "Make LLM quality measurable and its regression impossible to merge.",
          "es": "Que la calidad del LLM sea medible y su regresión, imposible de mergear."
        }
      },
      {
        "action": {
          "en": "Authored harness-standard: EARS specs, Leader/Spec Author/Implementer/Reviewer roles, human approval gates, 2-4 task batches, a reviewer who runs the checks itself.",
          "es": "Autoría de harness-standard: specs EARS, roles Leader/Spec Author/Implementer/Reviewer, human approval gates, batches de 2-4 tareas, revisor que ejecuta las pruebas él mismo."
        },
        "id": "ai-first-harness",
        "label": {
          "en": "Agentic with gates (harness-standard)",
          "es": "Agentic con gates (harness-standard)"
        },
        "result": {
          "en": "Every task lands with green tests and independent review; the method is public, installable and in daily use — demonstrable agentic reliability.",
          "es": "Cada tarea llega con tests en verde y revisión independiente; el método es público, instalable y está en uso diario — fiabilidad agentic demostrable."
        },
        "situation": {
          "en": "Coding agents drift, and quality can't depend on the dispatcher's memory.",
          "es": "Los agentes de código derivan y la calidad no puede depender de la memoria de quien despacha."
        },
        "task": {
          "en": "Install a process that verifies agent output before it reaches main.",
          "es": "Instalar un proceso que verifique lo que producen los agentes antes de que llegue a main."
        }
      },
      {
        "action": {
          "en": "ADR-0004: pgvector versus Qdrant on operations, cost and maturity criteria; nomic embeddings with a local model (llama.cpp) to avoid external API dependency.",
          "es": "ADR-0004: pgvector vs Qdrant con criterios de operación, coste y madurez; embeddings nomic con modelo local (llama.cpp) para no depender de APIs externas."
        },
        "id": "rag-architecture-decision",
        "label": {
          "en": "RAG architecture decision (pgvector vs Qdrant ADR)",
          "es": "Decisión de arquitectura RAG (ADR pgvector vs Qdrant)"
        },
        "result": {
          "en": "A documented, reversible decision with the trade-off explicit — exactly the 'awareness of limitations' the role asks for.",
          "es": "Decisión documentada y reversible, con el trade-off explícito — exactamente la 'consciencia de limitaciones' que pide el rol."
        },
        "situation": {
          "en": "Choosing a vector store for a RAG with simple-deployment and cost constraints: options with fanboys on both shores.",
          "es": "Elegir vector store para un RAG con restricciones de despliegue simple y coste: opciones con fanboys a ambas orillas."
        },
        "task": {
          "en": "Decide with explicit criteria and leave the decision traceable for whoever comes next.",
          "es": "Decidir con criterios explícitos y dejar la decisión trazable para quien venga después."
        }
      },
      {
        "action": {
          "en": "Idempotent hub (upsert by natural key), DLT with retries, per-episode alerts (3 consecutive DOWN → 1 alert), hexagonal per service, Testcontainers + EmbeddedKafka.",
          "es": "Hub idempotente (upsert por clave natural), DLT con retries, alertas por episodio (3 DOWN consecutivos → 1 alerta), hexagonal por servicio y Testcontainers + EmbeddedKafka."
        },
        "id": "pipelines-idempotency",
        "label": {
          "en": "Idempotent pipelines (kafka-adapter-telemetry)",
          "es": "Pipelines idempotentes (kafka-adapter-telemetry)"
        },
        "result": {
          "en": "An e2e demo from scratch: idempotency verified by count and exactly one alert per episode; 3 ADRs document the decisions.",
          "es": "Demo e2e desde cero: idempotencia por recuento verificada y exactamente una alerta por episodio; 3 ADRs documentan las decisiones."
        },
        "situation": {
          "en": "Telemetry from ~90 adapters over Kafka: duplicates and corrupt JSON are the norm, not the exception.",
          "es": "Telemetría de ~90 adaptadores por Kafka: duplicados y JSON corrupto son la norma, no la excepción."
        },
        "task": {
          "en": "Duplicate-free Oracle persistence and reliable alerts despite producer retries.",
          "es": "Persistencia en Oracle sin duplicados y alertas fiables pese a los reintentos del productor."
        }
      },
      {
        "action": {
          "en": "Migration governance (audit, waves, decision traceability) plus a 12+ tool CLI suite that made doing the right thing easy and the wrong thing visible.",
          "es": "Governance de la migración (auditoría, olas, trazabilidad de decisiones) y una suite CLI de 12+ herramientas que hacía lo correcto fácil y lo incorrecto visible."
        },
        "id": "lead-influence-precedents",
        "label": {
          "en": "Multi-team influence (Mapfre + CLI suite)",
          "es": "Influencia multi-equipo (Mapfre + suite CLI)"
        },
        "result": {
          "en": "39 APIs on one stack and the suite adopted as the operating standard — influence through usefulness, not hierarchy.",
          "es": "39 APIs al mismo stack y la suite adoptada como estándar de operación — influencia por utilidad, no por jerarquía."
        },
        "situation": {
          "en": "39 corporate APIs owned by different teams with mismatched standards; nobody had formal authority over everyone.",
          "es": "39 APIs corporativas con equipos distintos y estándares dispares; nadie tenía autoridad formal sobre todos."
        },
        "task": {
          "en": "Drive the modernization and get the standard adopted without a decree.",
          "es": "Consolidar la modernización y que el estándar se adopte sin decreto."
        }
      }
    ]
  },
  "extia": {
    "brief": {
      "en": "Extia: a French ESN (2,500+ people). The AI variant: Python (FastAPI/Flask) + TypeScript (React/Next), RAG (LangChain/LlamaIndex), vector DBs (Chroma/Pinecone), Docker/K8s/cloud, fluent English. Band 40-55k. Real value depends on the assigned client (ESN = bench). The profile fits through RAG with CI evals — their stated pain is exactly 'we don't want people who only prompt'.",
      "es": "Extia: ESN francesa (2.500+ personas). Variante AI: Python (FastAPI/Flask) + TypeScript (React/Next), RAG (LangChain/LlamaIndex), vector DBs (Chroma/Pinecone), Docker/K8s/cloud, inglés fluido. Banda 40-55k. El valor real depende del cliente asignado (ESN = bench). El perfil encaja por RAG con evals en CI — su repte es exactamente 'no queremos gente que solo haga prompting'."
    },
    "company": "Extia",
    "gaps": [
      {
        "probe": {
          "en": "No first-hand evidence — declared in the cover letter. Position it: in-house vs API vs open-source decisions documented in ADRs; fine-tuning as the last resort after RAG and prompt engineering, not the first instinct.",
          "es": "Sin evidencia propia — declarado en la carta. Posicionarlo: decisiones in-house vs API vs open-source documentadas en ADRs; fine-tuning como última opción tras RAG y prompt engineering, no como primer instinto."
        },
        "topic": "Fine-tuning"
      },
      {
        "probe": {
          "en": "Honest minimum: solid TS, Astro and Next on own projects (jordimp.net on Astro); survival-level React/Next to pair-program, not to sell frontend seniority.",
          "es": "Mínimo honesto: TS sólido, Astro y Next en proyectos propios (jordimp.net en Astro); React/Next de sobrevivencia para pair-programming, no para vender seniority frontend."
        },
        "topic": "React/Next (frontend)"
      },
      {
        "probe": {
          "en": "Limited direct experience: RAG built by hand (CodebaseRAG) with nomic embeddings and llama.cpp — the advantage is understanding what those frameworks abstract and when they're superfluous.",
          "es": "Experiencia directa limitada: RAG construido a mano (CodebaseRAG) con embeddings nomic y llama.cpp — la ventaja es entender qué abstraen esos frameworks y cuándo sobran."
        },
        "topic": "LangChain/LlamaIndex"
      },
      {
        "probe": {
          "en": "B2 speaking: written is proven (cover letter, READMEs, ADRs in English). Rehearse the 15-minute eval-baseline demo out loud.",
          "es": "B2 speaking: el written ya está demostrado (carta, READMEs, ADRs en inglés). Ensayar en voz alta la demo de 15' del eval baseline."
        },
        "topic": "Inglés hablado"
      }
    ],
    "id": "extia",
    "role": {
      "en": "Fullstack AI Engineer (Barcelona / full remote Spain)",
      "es": "Fullstack AI Engineer (Barcelona / full remote España)"
    },
    "stages": [
      {
        "focus": {
          "en": "Clarify WHICH client/project (an ESN's value depends 100% on that), band (target 55k, AI profile + 9 years) and offer the eval-baseline demo.",
          "es": "Aclarir QUÉ cliente/proyecto (el valor de una ESN depende 100% de eso), banda (objetivo 55k, perfil AI + 9 años) y ofrecer la demo del eval baseline."
        },
        "id": "screen",
        "label": {
          "en": "Screen (recruiter)",
          "es": "Screen (recruiter)"
        },
        "questions": [
          {
            "en": "Introduce yourself in two minutes: what you build and why AI engineering.",
            "es": "Preséntate en dos minutos: qué construyes y por qué AI engineering."
          },
          {
            "en": "What is your RAG experience and with which tools?",
            "es": "¿Qué experiencia tienes con RAG y con qué herramientas?"
          },
          {
            "en": "How do you handle the frontend on fullstack projects?",
            "es": "¿Cómo trabajas el frontend en proyectos fullstack?"
          },
          {
            "en": "What is your salary expectation for full remote?",
            "es": "¿Qué expectativa salarial tienes para full remote?"
          }
        ]
      },
      {
        "focus": {
          "en": "The 15-minute CodebaseRAG eval-baseline demo is ready: 40+ Q/A golden set, committed recall@5 0.409, CI eval gate. Vector DBs: the pgvector vs Qdrant ADR decision; local nomic embeddings.",
          "es": "Demo de 15' del eval baseline de CodebaseRAG lista: golden set 40+ Q/A, recall@5 0.409 committed, eval gate en CI. Vector DBs: decisión pgvector vs Qdrant en ADR; embeddings nomic locales."
        },
        "id": "rag_deep",
        "label": {
          "en": "Technical: RAG and vector DBs",
          "es": "Técnico: RAG y vector DBs"
        },
        "questions": [
          {
            "en": "Explain your RAG pipeline: chunking, embeddings, retrieval and generation.",
            "es": "Explica tu pipeline RAG: chunking, embeddings, retrieval y generación."
          },
          {
            "en": "How do you measure RAG quality and what do you do when it drops?",
            "es": "¿Cómo mides la calidad de un RAG y qué haces cuando baja?"
          },
          {
            "en": "pgvector, Chroma, Pinecone: how would you choose a vector store for a project?",
            "es": "pgvector, Chroma, Pinecone: ¿cómo elegirías vector store para un proyecto?"
          },
          {
            "en": "When would you use LangChain and when would you build it by hand?",
            "es": "¿Cuándo usarías LangChain y cuándo lo construirías a mano?"
          },
          {
            "en": "Tell me about a case where RAG was the wrong solution.",
            "es": "Cuéntame un caso donde RAG no era la solución."
          }
        ]
      },
      {
        "focus": {
          "en": "Real TS/Next/Astro, honest survival-level React. Full DevOps: Docker/K8s, CI/CD (Jenkins, GH Actions), AWS (Lambda, CDK).",
          "es": "TS/Next/Astro reales, React de supervivencia honesto. DevOps sencer: Docker/K8s, CI/CD (Jenkins, GH Actions), AWS (Lambda, CDK)."
        },
        "id": "fullstack_devops",
        "label": {
          "en": "Fullstack + DevOps",
          "es": "Fullstack + DevOps"
        },
        "questions": [
          {
            "en": "How do you structure a FastAPI service: layers, I/O at the edges, testing?",
            "es": "¿Cómo estructuras un servicio FastAPI: capas, I/O en bordes, testing?"
          },
          {
            "en": "Walk me through your flow to dockerize and deploy a service.",
            "es": "Cuéntame tu flujo para dockerizar y desplegar un servicio."
          },
          {
            "en": "What have you built with TypeScript on the frontend?",
            "es": "¿Qué has construido con TypeScript en el frontend?"
          },
          {
            "en": "How do you guarantee Python quality: pytest, mypy, ruff, pre-commit?",
            "es": "¿Cómo garantizas calidad en Python: pytest, mypy, ruff, pre-commit?"
          }
        ]
      }
    ],
    "stories": [
      {
        "action": {
          "en": "A 40+ Q/A golden set, recall@5 with a committed baseline (0.409), a CI eval gate that blocks regressions; nomic embeddings and a local LLM via llama.cpp to avoid external API dependency.",
          "es": "Golden set de 40+ Q/A, recall@5 con baseline committed (0.409), eval gate en CI que bloquea regresiones; embeddings nomic y LLM local con llama.cpp para no depender de APIs externas."
        },
        "id": "rag-with-evals",
        "label": {
          "en": "RAG with evals (CodebaseRAG)",
          "es": "RAG con evals (CodebaseRAG)"
        },
        "result": {
          "en": "Measurable quality in CI and a replicable 15-minute demo — the reliability evidence behind their 'we don't want people who only prompt'.",
          "es": "Calidad medible en CI y demo de 15' replicable — la evidencia de fiabilidad que la oferta llama 'no queremos gente que solo haga prompting'."
        },
        "situation": {
          "en": "A repository RAG where 'it seems to answer well' is not an acceptance criterion.",
          "es": "Un RAG sobre repositorios donde 'parece que responde bien' no es un criterio de aceptación."
        },
        "task": {
          "en": "Prove it's not just prompting: measure, gate and ship LLM quality.",
          "es": "Demostrar que no solo se hace prompting: medir, gatear y shipejar la calidad del LLM."
        }
      },
      {
        "action": {
          "en": "An MCP server with structured input (tool schema), explicit error handling and an installable package.",
          "es": "Servidor MCP con entrada estructurada (tool schema), manejo de errores explícito y empaquetado instalable."
        },
        "id": "mcp-server",
        "label": {
          "en": "MCP server (mcp-transparent-png)",
          "es": "MCP server (mcp-transparent-png)"
        },
        "result": {
          "en": "A tool used by agents in real flows: evidence of tool/agent integration beyond chat.",
          "es": "Herramienta usada por agentes en flujos reales: evidencia de integración tool/agent más allá del chat."
        },
        "situation": {
          "en": "Agents needed a real transparency tool for PNGs (rgb/auto/greenscreen modes).",
          "es": "Los agentes necesitaban una herramienta real de transparencia para PNG (modos rgb/auto/greenscreen)."
        },
        "task": {
          "en": "Expose it as an MCP server on Python 3.13+ usable from real agents, not just a script.",
          "es": "Exponerla como servidor MCP en Python 3.13+ usable desde agentes reales, no solo como script."
        }
      },
      {
        "action": {
          "en": "TDD, strict mypy, GitHub Actions CI and orderly releases; every change with tests first.",
          "es": "TDD, mypy strict, CI en GitHub Actions y releases ordenadas; cada cambio con pruebas primero."
        },
        "id": "public-quality",
        "label": {
          "en": "Public quality (md-mermaid-pdf)",
          "es": "Calidad pública (md-mermaid-pdf)"
        },
        "result": {
          "en": "A stable public project with a green pipeline as the norm — verifiable proof of quality discipline.",
          "es": "Proyecto público estable con pipeline verde como norma — prueba verificable de disciplina de calidad."
        },
        "situation": {
          "en": "An MIT CLI rendering Markdown+Mermaid to PDF, in public: quality can no longer be 'trust me'.",
          "es": "Una CLI MIT que renderiza Markdown+Mermaid a PDF, en público: la calidad ya no puede ser 'confía en mí'."
        },
        "task": {
          "en": "Run a public project to the same standard as a demanding client.",
          "es": "Mantener un proyecto público con el mismo estándar que en un cliente exigente."
        }
      },
      {
        "action": {
          "en": "Astro 5 with a custom style, trilingual content validated with schemas, a Spring status-api with SSE and a FastAPI ask-api with RAG — deployed and live.",
          "es": "Astro 5 con estil propio, contenido trilingüe validado con schemas, status-api en Spring con SSE y ask-api FastAPI con RAG — desplegados y vivos."
        },
        "id": "fullstack-real",
        "label": {
          "en": "Real fullstack (jordimp.net on Astro + APIs)",
          "es": "Fullstack real (jordimp.net en Astro + APIs)"
        },
        "result": {
          "en": "A production site with real APIs: end-to-end demonstrable fullstack, with the honest React/Next gap declared up front.",
          "es": "Sitio en producción con APIs reales: fullstack demostrable de punta a punta, con el hueco honesto en React/Next declarado de antemano."
        },
        "situation": {
          "en": "A trilingual personal site with live APIs: Astro front and Java/Spring (SSE) + Python/FastAPI (CV RAG) backend.",
          "es": "Web personal bilingüe/trilingüe con APIs vivas: front Astro y backend Java/Spring (SSE) + Python/FastAPI (RAG del CV)."
        },
        "task": {
          "en": "Build and run the full stack alone: front, backend, homelab deploy and own domain.",
          "es": "Construir y operar el stack completo solo: front, backend, deploy en homelab y dominio propio."
        }
      },
      {
        "action": {
          "en": "Docker/K8s, AWS (Lambda, CDK, CloudFormation), Jenkins/GitHub Actions pipelines, SonarQube, docs and diagrams generated in CI.",
          "es": "Docker/K8s, AWS (Lambda, CDK, CloudFormation), pipelines Jenkins/GitHub Actions, SonarQube, documentación y diagramas generados en CI."
        },
        "id": "devops-ownership",
        "label": {
          "en": "End-to-end DevOps (AWS + CI/CD)",
          "es": "DevOps de punta a punta (AWS + CI/CD)"
        },
        "result": {
          "en": "Services deployed and run by the same team that wrote them, with observability as part of the deliverable.",
          "es": "Servicios desplegados y operados por el mismo equipo que los escribió, con la observabilidad como parte del entregable."
        },
        "situation": {
          "en": "Microservices that couldn't rely on a dedicated platform team.",
          "es": "Microservicios que no podían depender de un equipo de plataforma dedicado."
        },
        "task": {
          "en": "Run what you build: deploy, observe and maintain what was built.",
          "es": "Run what you build: desplegar, observar y mantener lo construido."
        }
      }
    ]
  },
  "preply": {
    "brief": {
      "en": "Preply: learning marketplace (Series D), cross-functional squad shipping features via A/B tests. Python/Django stack but tech-agnostic (Java/Spring welcome). On-call 1 week in 5, English minimum B2. Profile strengths: third-party integrations (~90 adapters) and test culture; only real gap: Django (FastAPI/Flask as conversion).",
      "es": "Preply: marketplace de aprendizaje (Series D), squad cross-functional con features lanzadas vía A/B tests. Stack Python/Django pero tech-agnostic (Java/Spring bienvenido). On-call 1 semana cada 5, inglés mínimo B2. Fort del perfil: integraciones de terceros (~90 adaptadores) y cultura de tests; único gap real: Django (FastAPI/Flask como conversión)."
    },
    "company": "Preply",
    "gaps": [
      {
        "probe": {
          "en": "Quick tour: ORM and querysets, migrations (vs Alembic), middleware (vs FastAPI dependencies), per-environment settings, Django admin. Position it as a conversion from SQLAlchemy/FastAPI, not a from-zero start.",
          "es": "Tour rápido: ORM y querysets, migrations (vs Alembic), middleware (vs FastAPI dependencies), settings por entorno, Django admin. Posicionarlo como conversión desde SQLAlchemy/FastAPI, no como arranque de cero."
        },
        "topic": "Django"
      },
      {
        "probe": {
          "en": "Experiment culture: hypothesis, primary metric and guardrails, basic sample size, when to stop, risks of peeking early. The data-science MSc is the bridge.",
          "es": "Cultura de experimentos: hipótesis, métrica primaria y guardrails, tamaño de muestra básico, cuándo parar, riesgos de mirar pronto el resultado. El MSc de datos es el puente."
        },
        "topic": "A/B testing"
      },
      {
        "probe": {
          "en": "Vendor-integration stories (webhooks, payments, sync) reframed for a marketplace: two platform sides and network effects.",
          "es": "Historias de integración con proveedores externos (webhooks, pagos, sincronización) traducidas a marketplace: dos lados de la plataforma y efectos de red."
        },
        "topic": "Marketplace / vendors"
      },
      {
        "probe": {
          "en": "Minimum B2: rehearse a 15-minute pitch about the Open Gateway integrations out loud; it's the real filter (the Affirm lesson).",
          "es": "Mínimo B2: pitch de 15 minutos sobre integraciones Open Gateway ensayado en voz alta; es el filtro real (lección Affirm)."
        },
        "topic": "Inglés hablado"
      }
    ],
    "id": "preply",
    "role": {
      "en": "Senior Back-End Engineer (Barcelona, hybrid)",
      "es": "Senior Back-End Engineer (Barcelona, híbrido)"
    },
    "stages": [
      {
        "focus": {
          "en": "Confirm hybrid (days), salary band, the concrete squad and the spoken-English expectation. Make the Django conversion clear without overselling.",
          "es": "Confirmar híbrido (días), banda salarial, squad concreta y expectativa de inglés hablado. Dejar clara la conversión Django sin sobreventa."
        },
        "id": "screen",
        "label": {
          "en": "HR screen",
          "es": "HR screen"
        },
        "questions": [
          {
            "en": "Introduce yourself: your path into backend and what brings you to a learning marketplace.",
            "es": "Preséntate: tu camino al backend y qué te trae a un marketplace de aprendizaje."
          },
          {
            "en": "How would you approach learning Django coming from FastAPI and Spring?",
            "es": "¿Cómo abordarías aprender Django viniendo de FastAPI y Spring?"
          },
          {
            "en": "What is your experience with experimentation and A/B tests?",
            "es": "¿Qué experiencia tienes con experimentación y A/B tests?"
          },
          {
            "en": "How do you see yourself in a weekly on-call rotation?",
            "es": "¿Cómo te ves en un sistema de on-call semanal?"
          }
        ]
      },
      {
        "focus": {
          "en": "Django: ORM, migrations, middleware, admin. Experiments: what a well-run A/B looks like. Solid SQL as backup.",
          "es": "Django: ORM, migrations, middleware, admin. Experimentos: diseño de un A/B bien hecho. Sólido SQL como respaldo."
        },
        "id": "backend_deep",
        "label": {
          "en": "Backend deep dive (Django + experiments)",
          "es": "Técnica backend (Django + experimentos)"
        },
        "questions": [
          {
            "en": "Explain the Django ORM: N+1 queries, select_related versus prefetch_related.",
            "es": "Explica el ORM de Django: N+1, select_related vs prefetch_related."
          },
          {
            "en": "How would you evolve a production schema with Django migrations without downtime?",
            "es": "¿Cómo evolucionarías un schema en producción con migrations de Django sin cortar el servicio?"
          },
          {
            "en": "Design an A/B test for a new search feature: hypothesis, metric, sample size and risks.",
            "es": "Diseña un A/B test para una nueva feature de búsqueda: hipótesis, métrica, sample size y riesgos."
          },
          {
            "en": "An experiment shows +2% without significance after 3 days: what do you do?",
            "es": "Un experimento muestra +2% sin significancia a los 3 días: ¿qué haces?"
          },
          {
            "en": "Django middleware versus FastAPI dependencies: where would auth and telemetry go?",
            "es": "Middleware de Django vs dependencies de FastAPI: ¿dónde pondrías auth y telemetría?"
          }
        ]
      },
      {
        "focus": {
          "en": "Vendor stories: webhooks, idempotency, retries, reconciliation. On-call: run what you build, alerts and runbooks.",
          "es": "Historias de vendors: webhooks, idempotencia, retries, reconciliación. On-call: run what you build, alertas y runbooks."
        },
        "id": "vendor_integrations",
        "label": {
          "en": "Integrations and reliability",
          "es": "Integraciones y fiabilidad"
        },
        "questions": [
          {
            "en": "Tell me about a third-party integration that kept breaking: how you diagnosed and stabilized it.",
            "es": "Cuéntame una integración con un tercero que se rompía: cómo la diagnosticaste y la estabilizaste."
          },
          {
            "en": "How do you make a webhook-receiving endpoint idempotent?",
            "es": "¿Cómo haces idempotente un endpoint que recibe webhooks de un proveedor?"
          },
          {
            "en": "What have you run in production: metrics, alerts, and how did you sleep through on-call?",
            "es": "¿Qué has operado en producción: métricas, alertas y cómo dormiste con on-call?"
          },
          {
            "en": "Tell me about an incident with affected customers and what changed afterwards.",
            "es": "Cuéntame un incidente con clientes afectados y qué cambió después."
          }
        ]
      }
    ],
    "stories": [
      {
        "action": {
          "en": "A common pattern: idempotency, retries with backoff, acknowledgements, reconciliation; a 12+ tool CLI suite for pre-deploy checks and verification; docs generated in CI.",
          "es": "Patrón común: idempotencia, retries con backoff, acuses, reconciliación; suite CLI de 12+ herramientas para pre-deploy checks y verificación; documentación generada en CI."
        },
        "id": "vendor-integrations-career",
        "label": {
          "en": "Third-party integrations as a craft (~90 adapters)",
          "es": "Integraciones de terceros como oficio (~90 adaptadores)"
        },
        "result": {
          "en": "~90 adapters across 4 countries run to a single standard; third-party failures are absorbed without manual escalation.",
          "es": "~90 adaptadores en 4 países operados con estándar único; los fallos de tercero se absorben sin escalado manual."
        },
        "situation": {
          "en": "Open Gateway integrates heterogeneous operator APIs: every operator with its own errors and limits.",
          "es": "Open Gateway integra APIs de operadores heterogéneos: cada operador, sus errores y sus limites."
        },
        "task": {
          "en": "Run third-party integrations as a product — reliable, observable and tested, not glue code.",
          "es": "Operar integraciones de terceros como producto: fiables, observables y con pruebas, no como glue code."
        }
      },
      {
        "action": {
          "en": "On CodebaseRAG: a 40+ Q/A golden set, a committed baseline (recall@5 0.409) and a CI eval gate — every prompt or retrieval change is measured against the baseline before merge.",
          "es": "En CodebaseRAG: golden set de 40+ Q/A, baseline committed (recall@5 0.409) y eval gate en CI — cada cambio de prompt o retrieval se mide contra el baseline antes de mergear."
        },
        "id": "experiment-mindset",
        "label": {
          "en": "Experimental mindset (MSc + evals)",
          "es": "Mentalidad experimental (MSc + evals)"
        },
        "result": {
          "en": "Improvements are accepted on evidence and regressions are caught in CI — the same habit an A/B-test culture demands.",
          "es": "Las mejoras se aceptan por evidencia y las regresiones se detectan en CI; el mismo hábito que exige un culture de A/B tests."
        },
        "situation": {
          "en": "Backend-product decisions that intuition can't settle: which model, which retrieval, which change truly improves things.",
          "es": "Decisiones de producto backend que no se pueden decidir por intuición: qué modelo, qué retrieval, qué cambio mejora de verdad."
        },
        "task": {
          "en": "Bring the experimental method (from the data-science MSc) into everyday engineering decisions.",
          "es": "Llevar el método experimental (del MSc de datos) a decisiones de ingeniería cotidianas."
        }
      },
      {
        "action": {
          "en": "API-by-API audit, wave plan, homogeneous conventions, decision traceability and two-way reviews — the exact method I'd replicate for Django.",
          "es": "Auditoría API a API, plan de olas, convenciones homogéneas, trazabilidad de decisiones y revisiones bidireccionales — el método que replicaría para Django."
        },
        "id": "django-conversion",
        "label": {
          "en": "Stack conversion (FastAPI/SQLAlchemy → Django)",
          "es": "Conversión de stack (FastAPI/SQLAlchemy → Django)"
        },
        "result": {
          "en": "39 APIs modernized onto one stack; proof that framework switching is a solved problem for me.",
          "es": "39 APIs modernizadas al mismo stack; demuestra que el cambio de framework es un problema resuelto para mí."
        },
        "situation": {
          "en": "Mapfre: consolidating 39 corporate APIs onto a single stack (Node.js 24) — a stack change with consumers depending on you.",
          "es": "Mapfre: consolidar 39 APIs corporativas hacia un stack único (Node.js 24) — cambio de stack con consumidores dependiendo de ti."
        },
        "task": {
          "en": "Learn and standardize a new stack in production, with wave-based migrations and zero consumer breakage.",
          "es": "Aprender y estandarizar un stack nuevo en producción, con migraciones por olas y sin romper consumidores."
        }
      },
      {
        "action": {
          "en": "Daily TDD, Testcontainers for real integrations, SonarQube/SonarLint in the pipeline, two-way reviews (my code gets reviewed too).",
          "es": "TDD diario, Testcontainers para integraciones reales, SonarQube/SonarLint en pipeline, revisiones bidireccionales (también reviso mi propio código con otros)."
        },
        "id": "test-culture",
        "label": {
          "en": "Test and review culture",
          "es": "Cultura de tests y revisiones"
        },
        "result": {
          "en": "Suites people trust, running on every PR; quality stops being an event and becomes the path.",
          "es": "Suites en las que la gente confía y que se ejecutan en cada PR; la calidad deja de ser un evento y pasa a ser el camino."
        },
        "situation": {
          "en": "Teams where tests were ceremony: slow, brittle and distrusted.",
          "es": "Equipos donde los tests eran ceremonia: lentos, frágiles y sin confianza."
        },
        "task": {
          "en": "Make tests and reviews part of the flow, not a final gate.",
          "es": "Que las pruebas y las revisiones sean parte del flujo, no un filtro final."
        }
      },
      {
        "action": {
          "en": "Systematic root-cause analysis, reproduce before touching, fix with a regression test, parameterized logging and clear client-impact communication.",
          "es": "Root-cause analysis sistemático, reproducir antes de tocar, fix con regresión, logging parametrizado y comunicación del impacto al cliente."
        },
        "id": "on-call-readiness",
        "label": {
          "en": "On-call readiness (incidents with a price tag)",
          "es": "On-call readiness (incidentes con precio)"
        },
        "result": {
          "en": "Incidents resolved with documented causes and fewer repeats; fits a weekly on-call without heroics.",
          "es": "Incidentes resueltos con causa documentada y menos reincidencias; encaja con la on-call semanal sin heroísmos."
        },
        "situation": {
          "en": "Zitro: betting-engine server with real money — incidents don't allow 'we'll look at it tomorrow'.",
          "es": "Zitro: servidor del motor de apuestas con dinero real — los incidentes no admiten 'mañana lo miramos'."
        },
        "task": {
          "en": "Cut diagnosis time and repeat incidents in money-sensitive production.",
          "es": "Reducir el tiempo de diagnóstico y la reincidencia en producción sensible."
        }
      }
    ]
  },
  "yaba": {
    "brief": {
      "en": "Yaba: house of brands (supplements, health food, home) selling on Amazon, own Shopify, iHerb and Target. Small tech team, reporting to the CTO. Process of at most 3 interactions: people screen and a technical session with the team and CTO (real task with an AI coding agent on their repo + design conversation). Core requirement: AI-first — 'assume generated code is wrong until proven right'. Stack to discuss: NetSuite (SuiteTalk), EDI X12, Amazon SP-API, Shopify Admin API integrations, pricing back office.",
      "es": "Yaba: house of brands (suplementos, health food, hogar) vendiendo en Amazon, Shopify propio, iHerb y Target. Equipo técnico pequeño, reportas al CTO. Proceso de máximo 3 interacciones: people screen y técnica con el equipo y el CTO (tarea real con un AI coding agent en su repo + design conversation). Requisito central: AI-first — 'assume generated code is wrong until proven right'. Stack a tratar: integraciones NetSuite (SuiteTalk), EDI X12, Amazon SP-API, Shopify Admin API, pricing back office."
    },
    "company": "Yaba",
    "gaps": [
      {
        "probe": {
          "en": "No hands-on: integration discipline transfers, vocabulary doesn't. Be able to name SuiteTalk REST + SuiteQL and map it to what you already do (adapters, idempotency, reconciliation).",
          "es": "Sin experiencia: la disciplina de integración se traslada, el vocabulario no. Saber nombrar SuiteTalk REST + SuiteQL y mapearlo a lo que ya haces (adaptadores, idempotencia, reconciliación)."
        },
        "topic": "NetSuite / SuiteTalk"
      },
      {
        "probe": {
          "en": "Minimum vocabulary: 850=PO, 856=ASN, 810=invoice, 846=inventory. Frame it as another integration format with acknowledgements and retries — known territory.",
          "es": "Vocabulario mínimo: 850=PO, 856=ASN, 810=invoice, 846=inventory. Enmarcarlo como otro formato de integración con acuses y reintentos, terreno conocido."
        },
        "topic": "EDI X12"
      },
      {
        "probe": {
          "en": "Order/inventory/fulfilment lifecycle on marketplace and DTC: what changes versus the corporate APIs you operate (rate limits, tokens, webhooks, stock reconciliation).",
          "es": "Ciclo de vida de pedido/inventario/fulfilment en marketplace y DTC: qué cambia frente a las APIs corporativas que operas (rate limits, tokens, webhooks, reconciliación de stock)."
        },
        "topic": "Amazon SP-API / Shopify Admin API"
      },
      {
        "probe": {
          "en": "For the pricing tool: understand Amazon Buy Box and reference pricing, and how you'd design a price-rules back office with an audit trail.",
          "es": "Para la pricing tool: entender Buy Box y reference-price en Amazon, y cómo diseñarías un back office de reglas de precio con auditoría."
        },
        "topic": "Pricing (Buy Box, reference price)"
      },
      {
        "probe": {
          "en": "The central hook: you are the author of harness-standard (specs, roles, human approval gates, in daily use). Method: precise brief → generate → critical review (edge cases, failure modes, secrets) → tests → reconcile with the source system.",
          "es": "El hook central: eres el autor de harness-standard (specs, roles, human approval gates, en uso diario). Método: brief preciso → generar → revisar críticamente (edge cases, failure modes, secrets) → tests → reconciliar con el sistema fuente."
        },
        "topic": "AI-first: verificar código generado"
      }
    ],
    "id": "yaba",
    "role": {
      "en": "Senior Software Engineer, Commerce Systems (Barcelona, hybrid)",
      "es": "Senior Software Engineer, Commerce Systems (Barcelona, híbrido)"
    },
    "stages": [
      {
        "focus": {
          "en": "Confirm hybrid (days in BCN), team size, absence of equity, and fit with 'some responsibility' without a formal lead role.",
          "es": "Confirmar híbrido (días en BCN), tamaño del equipo, ausencia de equity, y encajar con 'algo de responsabilidad' sin role formal de lead."
        },
        "id": "people_screen",
        "label": {
          "en": "People screen",
          "es": "People screen"
        },
        "questions": [
          {
            "en": "Tell me who you are and why a generalist role on a small team fits you right now.",
            "es": "Cuéntame quién eres y por qué un rol generalista en un equipo pequeño te encaja ahora."
          },
          {
            "en": "What does 'end-to-end ownership' with a CTO as your only counterpart mean to you?",
            "es": "¿Qué significa para ti 'ownership end-to-end' con un CTO como único interlocutor?"
          },
          {
            "en": "Tell me about a time you worked without micromanagement: how did you organize the work?",
            "es": "Háblame de una vez que trabajaste sin microgestión: cómo organizaste el trabajo."
          },
          {
            "en": "What are your salary expectations? We publish 50-60k.",
            "es": "¿Qué expectativa salarial tienes? Publicamos 50-60k."
          }
        ]
      },
      {
        "focus": {
          "en": "Their filter is 'assume generated code is wrong until proven right'. Demonstrate method: precise brief, critical review (edge cases, failure modes, secrets), tests first, reconciliation with the source system. Bring commit examples using harness-standard.",
          "es": "Su filtro es 'assume generated code is wrong until proven right'. Demostrar método: brief preciso, revisión crítica (edge cases, failure modes, secrets), tests primero, reconciliación con el sistema fuente. Portar ejemplos de commits con harness-standard."
        },
        "id": "ai_task",
        "label": {
          "en": "Technical: real task with an AI coding agent",
          "es": "Técnica: tarea real con AI coding agent"
        },
        "questions": [
          {
            "en": "Your task was built by a coding agent: how do you know it is correct?",
            "es": "Tu tarea la hizo un agente de código: ¿cómo sabes que es correcta?"
          },
          {
            "en": "What is your process before accepting generated code: what do you review, and in what order?",
            "es": "¿Qué proceso sigues antes de aceptar código generado: qué revisas y en qué orden?"
          },
          {
            "en": "Tell me about a defect an agent slipped in and how you caught it.",
            "es": "Cuéntame un fallo que un agente te coló y cómo lo detectaste."
          },
          {
            "en": "How do you spec so the agent gets it right the first time — and what do you do when it still fails?",
            "es": "¿Cómo especificas para que el agente acierte a la primera — y qué haces cuando falla igualmente?"
          },
          {
            "en": "What role do tests play when AI writes 80% of the code?",
            "es": "¿Qué papel juegan los tests cuando el 80% del código lo escribe una IA?"
          }
        ]
      },
      {
        "focus": {
          "en": "Integrations with idempotency, retries, queues and reconciliation — your home turf of 4 years. Translate the e-commerce vocabulary (NetSuite, EDI, SP-API, Shopify) onto the adapters you already run.",
          "es": "Integraciones con idempotencia, retries, colas y reconciliación — tu terreno de 4 años. Traducir el vocabulario e-commerce (NetSuite, EDI, SP-API, Shopify) a los adaptadores que ya operas."
        },
        "id": "design_conversation",
        "label": {
          "en": "Design conversation (commerce integrations)",
          "es": "Design conversation (integraciones commerce)"
        },
        "questions": [
          {
            "en": "Design the order integration with a marketplace: webhooks, rate limits, retries and stock reconciliation.",
            "es": "Diseña la integración de pedidos con un marketplace: webhooks, rate limits, reintentos y reconciliación de stock."
          },
          {
            "en": "An order shows up duplicated between Shopify and the ERP: how do you detect and resolve it without double charging?",
            "es": "Un pedido aparece duplicado entre Shopify y el ERP: ¿cómo lo detectas y lo resuelves sin doble cobro?"
          },
          {
            "en": "How would you design the pricing tool: rules, change audit trail, and safety against wrong prices?",
            "es": "¿Cómo diseñarías la pricing tool: reglas, auditoría de cambios y seguridad frente a precios erróneos?"
          },
          {
            "en": "What does 'run what you build' mean to you, and how have you applied it to third-party integrations?",
            "es": "Qué significa para ti 'run what you build' y cómo lo has aplicado a integraciones de terceros?"
          },
          {
            "en": "Tell me about an integration you ran in production: what broke and how you hardened it.",
            "es": "Cuéntame una integración que operaste en producción: qué fallaba y cómo lo endureciste."
          }
        ]
      }
    ],
    "stories": [
      {
        "action": {
          "en": "Authored harness-standard: Leader/Spec Author/Implementer/Reviewer roles, EARS specs, human approval gates, 2-4 task batches, traceability checking; installed and in daily use on real projects.",
          "es": "Autoría de harness-standard: roles Leader/Spec Author/Implementer/Reviewer, specs EARS, gates de aprobación humana, batches de 2-4 tareas, verificación de trazabilidad; instalado y en uso diario en proyectos reales."
        },
        "id": "ai-first-harness",
        "label": {
          "en": "AI-first: author of harness-standard",
          "es": "AI-first: autor de harness-standard"
        },
        "result": {
          "en": "Generated code arrives verified: every task lands with green tests and independent review before 'done'; the method is public and installable with one command.",
          "es": "El código generado llega verificado: cada tarea con tests en verde y revisión independiente antes de 'done'; el método es público e instalable con un comando."
        },
        "situation": {
          "en": "Coding agents drift: brilliant on one file, lost across a repo. Quality can't depend on remembering rules.",
          "es": "Los agentes de código derivan: brillantes en un fichero, perdidos en un repo. La calidad no puede depender de recordar reglas."
        },
        "task": {
          "en": "Turn the way of working with agents into an installable, repeatable process — not advice.",
          "es": "Convertir la forma de trabajar con agentes en un proceso instalable y repetible, no en consejos."
        }
      },
      {
        "action": {
          "en": "Common adapter pattern: idempotency, retries with backoff, queues, explicit acknowledgements and reconciliation; own tooling to verify every deployment.",
          "es": "Patrón común de adaptador: idempotencia, retries con backoff, colas, acuses explícitos y reconciliación; tooling propio para verificar cada despliegue."
        },
        "id": "integration-discipline",
        "label": {
          "en": "Integration discipline (~90 adapters)",
          "es": "Disciplina de integración (~90 adaptadores)"
        },
        "result": {
          "en": "Integrations that recover from third-party failures on their own, and deployments verifiable systematically across the 4 countries.",
          "es": "Integraciones que se recuperan solas de fallos de tercero y despliegues verificables sistemáticamente en los 4 países."
        },
        "situation": {
          "en": "Open Gateway: ~90 operator REST adapters across 4 countries and 5-6 environments, each with its quirks.",
          "es": "Open Gateway: ~90 adaptadores REST de operadores en 4 países y 5-6 entornos, cada uno con sus particularidades."
        },
        "task": {
          "en": "Make integrations survive third-party failure: duplicates, outages and partial responses.",
          "es": "Que las integraciones sobrevivan a los fallos de tercero: duplicados, caídas y respuestas parciales."
        }
      },
      {
        "action": {
          "en": "A suite of 12+ Python CLIs: pre-deploy checks, deployment verification, state queries, automatic docs and diagram generation in CI/CD.",
          "es": "Suite de más de 12 CLIs en Python: pre-deploy checks, verificación de despliegues, consultas de estado, generación automática de documentación y diagramas en CI/CD."
        },
        "id": "run-what-you-build",
        "label": {
          "en": "Run what you build (12+ CLI suite)",
          "es": "Run what you build (suite CLI 12+)"
        },
        "result": {
          "en": "The deploy-verify cycle is repeatable and docs generate themselves; repetitive operational errors disappeared.",
          "es": "El ciclo desplegar-verificar es repetible y la documentación se genera sola; los errores operativos repetitivos desaparecieron."
        },
        "situation": {
          "en": "Operating ~90 adapters by hand produced repetitive errors and stale documentation.",
          "es": "Operar ~90 adaptadores a mano generaba errores repetitivos y documentación obsoleta."
        },
        "task": {
          "en": "Give the team purpose-built operations tooling instead of manual runbooks.",
          "es": "Dar al equipo herramientas de operación propias en lugar de depender de runbooks manuales."
        }
      },
      {
        "action": {
          "en": "SDD with specs and ADRs, hexagonal per service, idempotent Oracle persistence, per-episode alerts (3 consecutive DOWN → 1 alert), DLT with retries, Testcontainers + EmbeddedKafka.",
          "es": "SDD con specs y ADRs, hexagonal por servicio, persistencia idempotente en Oracle, alertas por episodio (3 DOWN consecutivos → 1 alerta), DLT con retries, Testcontainers + EmbeddedKafka."
        },
        "id": "greenfield-end-to-end",
        "label": {
          "en": "Greenfield end-to-end (kafka-adapter-telemetry)",
          "es": "Greenfield end-to-end (kafka-adapter-telemetry)"
        },
        "result": {
          "en": "An e2e demo from scratch verifies idempotency by count and one alert per episode; public README and 3 ADRs as evidence.",
          "es": "Demo e2e desde cero verifica idempotencia por recuento y una alerta por episodio; README y 3 ADRs públicos como evidencia."
        },
        "situation": {
          "en": "A from-scratch personal project: adapter telemetry (gateway → Kafka → hub → Oracle) to demonstrate the full method.",
          "es": "Proyecto propio desde cero: telemetría de adaptadores (gateway → Kafka → hub → Oracle) donde demostrar método completo."
        },
        "task": {
          "en": "Build an idempotent, observable system to the same standard a demanding client would set.",
          "es": "Construir un sistema idempotente y observable con el mismo estándar que exigiría un cliente exigente."
        }
      },
      {
        "action": {
          "en": "Public TDD + strict mypy + CI (md-mermaid-pdf); on CodebaseRAG, a 40+ Q/A golden set and a CI eval gate with a committed baseline (recall@5 0.409).",
          "es": "TDD + mypy strict + CI públicos (md-mermaid-pdf); en CodebaseRAG, golden set de 40+ Q/A y eval gate en CI con baseline committed (recall@5 0.409)."
        },
        "id": "quality-gates",
        "label": {
          "en": "Quality gates (public TDD + eval gate)",
          "es": "Quality gates (TDD público + eval gate)"
        },
        "result": {
          "en": "Any RAG degradation fails in CI before release; the public CLI keeps its standard with tests first.",
          "es": "Cualquier degradación del RAG salta en CI antes de publicar; la CLI pública mantiene su estándar con pruebas primero."
        },
        "situation": {
          "en": "In AI projects (repo RAG) output quality isn't visible to the naked eye.",
          "es": "En proyectos con IA (RAG sobre repos) la calidad del output no se ve a simple vista."
        },
        "task": {
          "en": "Make quality measurable and regressions impossible to sneak in.",
          "es": "Que la calidad sea medible y las regresiones, imposibles de colar."
        }
      }
    ]
  }
};
})();
