#!/usr/bin/env python3
"""build-offer-sets.py — compile offer question sets into a file://-loadable bundle.

Source of truth:  <repo>/../../apply/sets/<empresa>.json   (outside this repo)
Output:           js/offer-sets.js  ->  window.OFFER_SETS = { id: set, ... }

A raw .json file is not a valid JS statement, so a `<script src>` cannot load
it directly on file://; this script wraps the validated sets in a plain JS
assignment (CONTRACTS.md §5). Run offline, stdlib only, idempotent:

    python3 scripts/build-offer-sets.py [--sets-dir DIR]

Validation fails loudly (file + reason) and writes nothing on error.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SETS = ROOT.parent.parent / "apply" / "sets"
OUT = ROOT / "js" / "offer-sets.js"

HEADER = (
    "/* == generated by scripts/build-offer-sets.py — DO NOT EDIT ==\n"
    "   Source of truth: apply/sets/<empresa>.json (outside this repo).\n"
    "   Rebuild: python3 scripts/build-offer-sets.py */\n"
)

errors = []


def err(fname, path, msg):
    errors.append(f"{fname}: {path}: {msg}")


def is_l10n(obj, fname, path, required=True):
    """A localized value: {"es": str, "en": str}, both non-empty."""
    if obj is None:
        if required:
            err(fname, path, "missing (expected {es, en})")
        return
    if not isinstance(obj, dict):
        err(fname, path, "not an object {es, en}")
        return
    for lang in ("es", "en"):
        v = obj.get(lang)
        if not isinstance(v, str) or not v.strip():
            err(fname, path, f".{lang} missing or empty")


def validate(fname, data):
    if not isinstance(data, dict):
        err(fname, "$", "root is not an object")
        return None
    for field in ("id", "company"):
        v = data.get(field)
        if not isinstance(v, str) or not v.strip():
            err(fname, f"$.{field}", "missing or empty")
    set_id = data.get("id") or "?"

    for field in ("role", "brief"):
        is_l10n(data.get(field), fname, f"$.{field}")

    gaps = data.get("gaps", [])
    if not isinstance(gaps, list):
        err(fname, "$.gaps", "not an array")
    for i, gap in enumerate(gaps):
        if not isinstance(gap, dict) or not isinstance(gap.get("topic"), str) or not gap["topic"].strip():
            err(fname, f"$.gaps[{i}]", "needs a non-empty 'topic'")
        is_l10n(gap.get("probe") if isinstance(gap, dict) else None,
                fname, f"$.gaps[{i}].probe")

    stages = data.get("stages")
    if not isinstance(stages, list) or not stages:
        err(fname, "$.stages", "must be an array with at least one stage")
        stages = []
    stage_ids = set()
    for i, stage in enumerate(stages):
        p = f"$.stages[{i}]"
        if not isinstance(stage, dict):
            err(fname, p, "not an object")
            continue
        sid = stage.get("id")
        if not isinstance(sid, str) or not sid.strip():
            err(fname, f"{p}.id", "missing or empty")
        elif sid in stage_ids:
            err(fname, f"{p}.id", f"duplicate stage id '{sid}'")
        else:
            stage_ids.add(sid)
        is_l10n(stage.get("label"), fname, f"{p}.label")
        is_l10n(stage.get("focus"), fname, f"{p}.focus", required=False)
        questions = stage.get("questions")
        if not isinstance(questions, list) or not questions:
            err(fname, f"{p}.questions", "must be a non-empty array")
            continue
        for j, q in enumerate(questions):
            is_l10n(q, fname, f"{p}.questions[{j}]")

    stories = data.get("stories", [])
    if not isinstance(stories, list):
        err(fname, "$.stories", "not an array")
    for i, story in enumerate(stories):
        p = f"$.stories[{i}]"
        if not isinstance(story, dict):
            err(fname, p, "not an object")
            continue
        if not isinstance(story.get("id"), str) or not story["id"].strip():
            err(fname, f"{p}.id", "missing or empty")
        is_l10n(story.get("label"), fname, f"{p}.label")
        for field in ("situation", "task", "action", "result"):
            is_l10n(story.get(field), fname, f"{p}.{field}")

    return set_id


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sets-dir", default=str(DEFAULT_SETS),
                    help=f"folder with <empresa>.json sets (default: {DEFAULT_SETS})")
    args = ap.parse_args()
    sets_dir = Path(args.sets_dir).resolve()

    if not sets_dir.is_dir():
        print(f"build-offer-sets: sets folder not found: {sets_dir}", file=sys.stderr)
        return 1
    files = sorted(sets_dir.glob("*.json"))
    if not files:
        print(f"build-offer-sets: no .json sets in {sets_dir}", file=sys.stderr)
        return 1

    bundle = {}
    ids_seen = {}
    for f in files:
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            err(f.name, "$", f"invalid JSON: {e}")
            continue
        set_id = validate(f.name, data)
        if set_id and not errors:
            if set_id in ids_seen:
                err(f.name, "$.id", f"duplicate set id '{set_id}' (also in {ids_seen[set_id]})")
            else:
                ids_seen[set_id] = f.name
                bundle[set_id] = data

    if errors:
        print("build-offer-sets: validation failed — nothing written:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    body = json.dumps(bundle, ensure_ascii=False, indent=2, sort_keys=True)
    js = (HEADER
          + "(function () {\n  \"use strict\";\n"
          + "  window.OFFER_SETS = " + body + ";\n"
          + "})();\n")

    OUT.write_text(js, encoding="utf-8")
    print(f"build-offer-sets: {len(bundle)} set(s) -> {OUT.relative_to(ROOT)} "
          f"({', '.join(sorted(bundle))})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
